{
    "0": "Ice Sign \"Icicle Fall Easy\"",
    "2": "Pimp Sign \"Bitch Slap\"",
    "6": "Extra Spell \"More Than Enough for a First Boss\"",
    "8": "\"Giga Wave\"",
    "9": "\"Hyper Wave\"",
    "10": "Flying Head \"Yukkuri Head\"",
    "14": "Engineer Sign \"Nope.avi\"",
    "16": "Engineer Sign \"Heck No\"",
    "18": "Streaming \"The lasers only hurt if you move\"",
    "20": "Streaming \"Stay Still\"",
    "21": "Streaming \"You'd Better Move\"",
    "22": "Lol \"Good Luck\"",
    "26": "Doge Sign \"Shibe of the Full Moon\"",
    "28": "Shibe Sign \"So Triangle\"",
    "30": "Shibe Sign \"So Star\"",
    "32": "Doge Sign \"u dont fukin control me\"",
    "34": "Doge Sign \"Attack on Shibe\"",
    "36": "Doge Sign \"fast doge\"",
    "38": "Doge Sign \"High-Speed Doge\"",
    "40": "Normal Sign \"Growl\"",
    "44": "Steel Sign \"Screech\"",
    "46": "Normal Sign \"Intimidate\"",
    "48": "Music Stand \"Music Staff of DOOM!!!!!!\"",
    "50": "Music Stand \"Music Staff of DEATH!!!\"",
    "51": "Music Stand \"Music Staff of DESTINY!\"",
    "52": "Normal Sign \"Hyper Voice\"",
    "56": "Normal Sign \"Echoed Voice\"",
    "58": "Echo Sign \"Echo Chamber\"",
    "60": "Stage 5 \"Scene Preview\"",
    "62": "Koto Music \"Social Upheaval Requiem\"",
    "64": "Bullshit Sign \"From the Bottom\"",
    "68": "Horizontal \"I'LL FLIP U M8\"",
    "70": "Horizontal \"YOU'VE BEEN FLIPPED\"",
    "72": "Bullshit Sign \"You Can't Do That\"",
    "74": "Vertical \"YOU CANNOT DO THAT!\"",
    "76": "Futo Arrow \"Previous Stage 5 Boss\"",
    "78": "\"Futo All Over Again\"",
    "80": "Milia Sign \"Primrose Shiver\"",
    "82": "All Over \"WHYYYYYYY\"",
    "84": "Small Bullets \"How Do I Dodge This?\"",
    "86": "Smaller Bullets \"You Don't Dodge This\"",
    "88": "Koishi and Utsuho \"Love Flare\"",
    "90": "\"Attack of the Luvdisc\"",
    "92": "Honedge \"Sword of 679 Years\"",
    "96": "\"Super Mushroom\"",
    "100": "Maze of Love 2 \"Electric Boogaloo\"",
    "102": "\"Rubik's 360\"",
    "104": "\"( ͡° ͜ʖ ͡°)\"",
    "106": "Seeing Double \"Trippin' PokéBalls\"",
    "108": "This one is shit \"It's like Eternal Meek on steroids\"",
    "109": "Prismriver 2 \"Electric Boogaloo\"",
    "110": "First Drum \"Rumble Temple Taiko\"",
    "111": "\"Some reflective shit\"",
    "112": "Donkey Kong \"Barrel Blast\"",
    "113": "Ground Type \"Earthquake\"",
    "114": "Curvy Lasers \"Aim for the Horn\"",
    "115": "\"Ultra Wall\"",
    "116": "BOOM ZOOM \"KAPOW PEW PEW ZOOOOOOOOOOM!\"",
    "117": "More Curvy Lasers \"Thunder Armor\"",
    "118": "\"Perish Song\"",
    "119": "\"ᕕ( ᐛ )ᕗ\""
}