{
    "th07 Menu Start": "Start the game",
    "th07 Menu Extra Start": "Start the extra stage",
    "th07 Menu Practice Start": "Select a stage, and start practicing",
    "th07 Menu Result": "View score and spell card history",
    "th07 Menu Music Room": "Listen to music",
    "th07 Menu Replay": "Watch the replays",
    "th07 Menu Option": "Change the settings",
    "th07 Menu Quit": "Quit the game",
    "th07 Option Player": "Choose the initial number of lives to start with. (Default: 3)",
    "th07 Option Graphic": "Change the color depth of the screen. 32-bit looks most beautiful.",
    "th07 Option BGM": "Change the method of playing BGM. (Default: WAV)",
    "th07 Option Sound": "Choose whether to play sound effects.",
    "th07 Option Window Mode": "Switch between full screen and windowed.",
    "th07 Option Slow Mode": "Slow down when there's a lot of bullets on screen. (no high score or replay though)",
    "th07 Option Reset": "Restore settings to default.",
    "th07 Option Key Config": "Configure key controls.",
    "th07 Option Quit": "Leave settings menu.",
    "th07 Key Shot": "Set shot/confirm button.",
    "th07 Key Bomb": "Set bomb/cancel button.",
    "th07 Key Slow": "Set the slow movement button.",
    "th07 Key Skip": "Set the skip message button.",
    "th07 Key Pause": "Set the pause button.",
    "th07 Key Up": "Set the button to move up.",
    "th07 Key Down": "Set the button to move down.",
    "th07 Key Left": "Set the button to move left.",
    "th07 Key Right": "Set the button to move right",
    "th07 Key ShotSlow": "Move slower when holding down the shot key.",
    "th07 Key Reset": "Restore settings to default.",
    "th07 Key Quit": "Leave button configuration.  ",
    "th08 Option BGM Volume": "Adjust the volume of the BGM.",
    "th08 Option SE Volume": "Adjust the volume of sound effects.",
    "th09 Menu Story Start": "Start the Story Mode",
    "th09 Menu Extra Start": "Start the Extra Mode",
    "th09 Menu Match Start": "Start with a PvP, vs. CPU, or watch mode",
    "th09 Menu Replay": "Playback replays",
    "th09 Menu Result": "See records",
    "th09 Menu Music Room": "Enter the music room",
    "th09 Option BGM": "Change the method of playing BGM. *MIDI isn't yet currently supported.",
    "th09 Option Key Config": "Setting the key controls",
    "th09 Key Side": "Select 1P or 2P.",
    "th09 Key Control Type": "PAD 1 or 2: use joypad; Full, Left, or Right: use keyboard.",
    "th09 Key Charge Type": "Change the behavior of the charge button",
    "th09 Key Shot": "Set the shot button",
    "th09 Key Bomb": "Set the bomb button",
    "th09 Key Slow": "Set the low speed or the charge button",
    "th06 Bomb Reimu A": "Spirit Sign \"Fantasy Seal\"",
    "th06 Bomb Reimu B": "Dream Sign \"Evil-Sealing Circle\"",
    "th06 Bomb Marisa A": "Imitation \"Stardust Reverie\"",
    "th06 Bomb Marisa B": "Malice Sign \"Light of Dawn\"",
    "th07 Bomb Reimu A unfocused": "Spirit Sign \"Fantasy Seal -Spread-\"",
    "th07 Bomb Reimu A focused": "Spirit Sign \"Fantasy Seal -Concentrate-\"",
    "th07 Bomb Reimu B focused": "Dream Sign \"Duplex Barrier\"",
    "th07 Bomb Marisa A focused": "Imitation \"Asteroid Belt\"",
    "th07 Bomb Marisa B unfocused": "Malice Sign \"Blind Laser\"",
    "th07 Bomb Sakuya A unfocused": "Illusion Sign \"Indiscriminate\"",
    "th07 Bomb Sakuya A focused": "Illusion Sign \"Killing Doll\"",
    "th07 Bomb Sakuya B unfocused": "Time Sign \"Perfect Square\"",
    "th07 Bomb Sakuya B focused": "Time Sign \"Private Square\"",
    "th08 Bomb Reimu": "Spirit Sign \"Fantasy Orb\"",
    "th08 Bomb Reimu Last": "Divine Spirit \"Fantasy Seal -Blink-\"",
    "th08 Bomb Yukari": "Border Sign \"Quadruple Barrier\"",
    "th08 Bomb Yukari Last": "Boundary \"Quadruple Barrier of the Imperishable Night\"",
    "th08 Bomb Marisa Last": "Magicannon \"Final Spark\"",
    "th08 Bomb Alice": "Malice Sign \"Ghastly Explosion\"",
    "th08 Bomb Alice Last": "Demonic Sign \"Spirit Kamikaze\"",
    "th08 Bomb Sakuya Last": "Buriallusion \"Phantomic Killer in Night Mist\"",
    "th08 Bomb Remilia": "Scarlet Sign \"Red the Nightless Castle\"",
    "th08 Bomb Remilia Last": "Scarlet Devil \"Scarlet Devil\"",
    "th08 Bomb Youmu": "Scepter \"Spiritual Slice\"",
    "th08 Bomb Youmu Last": "Scepter \"Phantomic Slash\"",
    "th08 Bomb Yuyuko": "Nature Sign \"Flower Shower\"",
    "th08 Bomb Yuyuko Last": "Poison Higanbana \"Flower Burial\"",
    "th08 Spell Dissolve": "\"Dissolve Spell\"",
    "th08 Spell Resurrection": "\"Resurrection\"",
    "th08 Music Room spoiler 1": "*** NOTE ***",
    "th08 Music Room spoiler 2": "This song hasn't been played in the game yet.",
    "th08 Music Room spoiler 3": "If you do not want to hear the song or see the comments, ",
    "th08 Music Room spoiler 4": "It is recommended that you stay away from here as soon as possible.",
    "th08 Music Room spoiler 5": "　",
    "th09 Music Room spoiler 1": "***** NOTE *****",
    "th09 Music Room spoiler 2": "This song hasn't been played in the game yet.",
    "th09 Music Room spoiler 3": "You can listen to a sample, but song titles can't be viewed.",
    "th10 Music Room spoiler 1": "<c$** Selected song has not yet been played in-game **$>",
    "th10 Music Room spoiler 2": "<c$Song comments may contain spoilers.$>",
    "th10 Music Room spoiler 3": "<c$Do you still wish to play this song?$>",
    "th10 Music Room spoiler 4": "<c$If you would like to play, please press the button again.$>",
    "th10 Music Room spoiler 5": "<c$If you do not want to play, please move the cursor.$>",
    "th13 spell nothing": "Nothing...",
    "th10 Dialog Prompt": "Please select a window mode.",
    "th10 Dialog Fullscreen": "Full screen",
    "th10 Dialog Always ask": "Always ask",
    "th11 Dialog Fullscreen 640": "Full screen (640×480)",
    "th11 Dialog Window 640": "Windowed (640×480)",
    "th11 Dialog Window 960": "Windowed (960×720)",
    "th11 Dialog Window 1280": "Windowed (1280×960)",
    "th11 Dialog Game Start": "Start",
    "th14 Dialog Prompt": "Select the resolution:",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720",
    "th14 Dialog 1280": "1280×960 (Recommended)",
    "th14 Dialog Fullscreen": "Play in full screen",
    "th14 Dialog Always ask": "Always ask",
    "alcostg JP": "Uwabami Breakers",
    "th128 JP": "Fairy Wars",
    "th06 config": "Touhou Koumakyou - Environment Custom Program",
    "th07 config": "Touhou Youyoumu - Environment Custom Program",
    "th08 config": "Touhou Eiyashou - Environment Custom Program",
    "th09 config": "Touhou Kaeidzuka - Environment Custom Program",
    "th095 config": "Touhou Bunkachou - Environment Custom Program",
    "th10 config": "Touhou Fuujinroku - Environment Custom Program",
    "alcostg config": "Uwabami Breakers - Environment Custom Program",
    "th11 config": "Touhou Chireiden - Environment Custom Program",
    "th12 config": "Touhou Seirensen - Environment Custom Program",
    "th125 config": "Double Spoiler - Environment Custom Program",
    "th128 config": "Fairy Wars - Environment Custom Program",
    "th13 config": "Touhou Shinreibyou - Environment Custom Program",
    "th14 config": "Touhou Kishinjou - Environment Custom Program",
    "th06 up": "Up ",
    "th06 down": "Down ",
    "th06 left": "Left ",
    "th06 right": "Right ",
    "th06 vertex": "Don't use the vertex buffer",
    "th06 fog": "Don't use fog",
    "th06 16bit textures": "16 Bit textures",
    "th06 Gouraud shading": "Suppress use of Gouraud shading",
    "th06 color composition": "Color composition isn't applied to textures",
    "th06 rasterizer mode": "Start in reference rasterizer mode",
    "th06 clear buffer": "Clear back buffer on refresh",
    "th06 minimum graphics": "Display minimum graphics needed",
    "th06 depth test": "Turn off the depth test",
    "th06 force frame": "Forcibly keep on 60 frames",
    "th06 fullscreen": "Full screen",
    "th06 windowed": "Windowed",
    "th06 full rate": "1/1 (default)",
    "th06 half rate": "1/2",
    "th06 third rate": "1/3",
    "th06 32bits mode": "32-bit",
    "th06 16bits mode": "16-bit",
    "th06 accept": "OK",
    "th06 cancel": "Cancel",
    "th06 screen mode": "Screen mode",
    "th06 refresh rate": "Frameskip",
    "th06 colors": "Color mode",
    "th06 pad X axis": "Pad X Axis (1–1000)",
    "th06 pad Y axis": "Pad Y Axis (1–1000)",
    "th06 check pad": "Check pad input",
    "th06 DirectInput": "Don't use the DirectInput pad",
    "th06 config saved caption": "OK",
    "th06 config saved text": "Configuration saved.",
    "th07 16bits textures": "Force using 16-bit textures",
    "th07 DirectInput": "Don't use DirectInput for input control",
    "th07 BGM memory": "Preload BGM in memory",
    "th07 draw screen": "Redraw HUD every frame",
    "th07 VSync": "Disable vertical synchronization",
    "th07 fullscreen": "Full screen (Rec.)",
    "th07 low effects": "Min.",
    "th07 medium effects": "Moderate",
    "th07 high effects": "Max (Rec.)",
    "th07 32bits mode": "32-bit (default)",
    "th07 effect quality": "Effect quality",
    "th08 fog": "Disable fog (not recommended)",
    "th08 color composition": "Don't use color composition textures (forbidden)",
    "th08 depth test": "Disable depth test (not recommended)",
    "th08 rasterizer mode": "Start in reference rasterizer mode (forbidden)",
    "th08 VSync": "Disable vertical synchronization (not recommended)",
    "th09 full rate": "None (default)",
    "th09 1P controller": "1P controller",
    "th09 2P controller": "2P controller",
    "th09 gamepad 1": "Gamepad 1",
    "th09 gamepad 2": "Gamepad 2",
    "th09 all keyboard": "Complete keyboard",
    "th09 left side keyboard": "Left",
    "th09 right side keyboard": "Right",
    "th09 no save": "Exit without saving",
    "th09 save": "Save and exit",
    "th10 faith meter": "Show faith meter near the player",
    "th10 screen mode": "Screen mode",
    "th10 always ask": "Always ask",
    "th10 slowshot": "Focus when firing",
    "th11 input latency": "Input latency",
    "th11 stable input": "Stable (if the input doesn't work often)",
    "th11 normal input": "Normal (low CPU usage)",
    "th11 automatic input": "Automatic (detect fastest response) *Default",
    "th11 fast input": "Fast (if automatic doesn't work correctly)",
    "th11 input description": "Select the type of latency for accurate input response.\n\"Stable\" and \"Normal\" respond to the input from the previous frame.\n\"Automatic\" will attempt to provide the fastest response possible.\n\"Fast\" will provide similar performance to \"Automatic,\" but video may be distorted.\n*Doesn't work with frameskip settings other than \"No skip\"*",
    "th11 always ask": "Always ask at startup",
    "th11 sensitivity description": "If the directional input is slow, increase the sensitivity.\n(default: 600)",
    "th11 joypad sensitivity": "Joypad sensitivity",
    "th11 default": "Restore all defaults",
    "th143 config": "Danmaku Amanojaku - Environment Custom Program",
    "th143 Trophy Format": "\"%s\"",
    "th143 Trophy Get": "Nickname earned",
    "th08 Music Room spoiler 6": "(Also, note that you can press the OK button here, along with the other songs,",
    "th08 Music Room spoiler 7": "to view the comment and play the theme, so be careful.)",
    "th08 Menu Spell Practice": "Practice a spell card against an opponent.",
    "th143 JP": "Danmaku Amanojaku"
}