{
    "th06_01": "A Dream that is more Scarlet than Red",
    "th06_02": "A Soul that is Red, like a Ground Cherry",
    "th06_03": "Apparitions Stalk the Night",
    "th06_04": "Lunate Elf",
    "th06_05": "Tomboyish Girl in Love",
    "th06_06": "Shanghai Teahouse ~ Chinese Tea",
    "th06_07": "Shanghai Alice of Meiji 17",
    "th06_08": "Voile, the Magic Library",
    "th06_09": "Locked Girl ~ The Girl's Secret Room",
    "th06_10": "The Maid and the Pocket Watch of Blood",
    "th06_11": "Lunar Clock ~ Luna Dial",
    "th06_12": "The Young Descendant of Țepeș",
    "th06_13": "Septette for a Dead Princess",
    "th06_14": "The Centennial Festival for Magical Girls",
    "th06_15": "U.N. Owen was Her?",
    "th06_16": "An Eternity More Transient than Scarlet",
    "th06_17": "Crimson Tower ~ Eastern Dream...",
    "th07_01": "Mystical Dream ~ Snow or Cherry Petal",
    "th07_02": "Paradise ~ Deep Mountain",
    "th07_03": "Crystalized Silver",
    "th07_04": "The Fantastic Tales from Tono",
    "th07_05": "Diao Ye Zong (withered leaf)",
    "th07_06": "The Doll Maker of București",
    "th07_07": "Doll Judgment ~ The Girl who Played with People's Shapes",
    "th07_08": "The Capital City of Flowers in the Sky",
    "th07_09": "Ghostly Band ~ Phantom Ensemble",
    "th07_10": "Eastern Mystical Dream ~ Ancient Temple",
    "th07_11": "Hiroari Shoots a Strange Bird ~ Till When?",
    "th07_12": "Ultimate Truth",
    "th07_13": "Bloom Nobly, Ink-black Cherry Blossom ~ Border of Life",
    "th07_14": "Border of Life",
    "th07_15": "Youkai Domination",
    "th07_16": "A Maiden's Illusionary Funeral ~ Necro-Fantasy",
    "th07_17": "Youkai Domination ~ Who done it!",
    "th07_18": "Necrofantasia",
    "th07_19": "Dream of a Spring Breeze",
    "th07_20": "Sakura, Sakura ~ Japanize Dream...",
    "th08_01": "Eternal Night Vignette ~ Eastern Night",
    "th08_02": "Illusionary Night ~ Ghostly Eyes",
    "th08_03": "Stirring a Fall Moon ~ Mooned Insect",
    "th08_04": "Song of the Night Sparrow ~ Night Bird",
    "th08_05": "Deaf to All but the Song",
    "th08_06": "Nostalgic Blood of the East ~ Old World",
    "th08_07": "Plain Asia",
    "th08_08": "Retribution for the Eternal Night ~ Imperishable Night",
    "th08_09": "Maiden's Capriccio ~ Dream Battle",
    "th08_10": "Complete Darkness",
    "th08_11": "Cinderella Cage ~ Kagome-Kagome",
    "th08_12": "Lunatic Eyes ~ Invisible Full Moon",
    "th08_13": "Voyage 1969",
    "th08_14": "Gensokyo Millennium ~ History of the Moon",
    "th08_15": "Flight in the Bamboo Cutter ~ Lunatic Princess",
    "th08_16": "Voyage 1970",
    "th08_17": "Extend Ash ~ Person of Hourai",
    "th08_18": "Reach for the Moon, Immortal Smoke",
    "th08_19": "Evening Primrose",
    "th08_20": "Eternal Dream ~ Mystical Maple",
    "th08_21": "Eastern Youkai Beauty",
    "th09_01": "Flower Viewing Mound ~ Higan Retour",
    "th09_02": "Spring Lane ~ Colorful Path",
    "th09_03": "Reincarnation",
    "th09_04": "Flowering Night",
    "th09_05": "Eastern Mystical Dream ~ Ancient Temple",
    "th09_06": "Lunatic Eyes ~ Invisible Full Moon",
    "th09_07": "Adventure of the Lovestruck Tomboy",
    "th09_08": "Ghostly Band ~ Phantom Ensemble",
    "th09_09": "Deaf to All but the Song ~ Flower Mix",
    "th09_10": "White Flag of Usa Shrine",
    "th09_11": "Wind God Girl",
    "th09_12": "Poison Body ~ Forsaken Doll",
    "th09_13": "Gensokyo, Past and Present ~ Flower Land",
    "th09_14": "Higan Retour ~ Riverside View",
    "th09_15": "Eastern Judgment in the Sixtieth Year ~ Fate of Sixty Years",
    "th09_16": "The Mound where the Flowers Reflect",
    "th09_17": "Mound of Life",
    "th09_18": "The Flower Like the Fantasy",
    "th09_19": "Flower of Soul ~ Another Dream...",
    "th095_01": "Tengu's Notebook ~ Mysterious Note",
    "th095_02": "Wind Circulation ~ Wind Tour",
    "th095_03": "Tengu is Watching ~ Black Eyes",
    "th095_04": "Sleepless Night of the Eastern Country",
    "th095_05": "Retrospective Kyoto",
    "th095_06": "Wind God Girl",
    "th10_01": "Sealed Gods",
    "th10_02": "A God That Misses People ~ Romantic Fall",
    "th10_03": "Because Princess Inada Is Scolding Me",
    "th10_04": "The Road of the Misfortune God ~ Dark Road",
    "th10_05": "Dark Side of Fate",
    "th10_06": "The Gensokyo the Gods Loved",
    "th10_07": "Akutagawa Ryuunosuke's \"Kappa\" ~ Candid Friend",
    "th10_08": "Fall of Fall ~ Autumnal Waterfall",
    "th10_09": "Youkai Mountain ~ Mysterious Mountain",
    "th10_10": "The Primal Scene of Japan the Girl Saw",
    "th10_11": "Faith Is for the Transient People",
    "th10_12": "Cemetery of Onbashira ~ Grave of Being",
    "th10_13": "The Venerable Ancient Battlefield ~ Suwa Foughten Field",
    "th10_14": "Tomorrow Will Be Special, Yesterday Was Not",
    "th10_15": "Native Faith",
    "th10_16": "Shrine at the Foot of the Mountain",
    "th10_17": "The Gods Give Us Blessed Rain ~ Sylphid Dream",
    "th10_18": "Player's Score",
    "th11_01": "Awakening of the Earth Spirits",
    "th11_02": "The Dark Blowhole",
    "th11_03": "The Sealed-Away Youkai ~ Lost Place",
    "th11_04": "The Bridge People No Longer Cross",
    "th11_05": "Green-Eyed Jealousy",
    "th11_06": "Walking the Streets of a Former Hell",
    "th11_07": "A Flower-Studded Sake Dish on Mt. Ooe",
    "th11_08": "Heartfelt Fancy",
    "th11_09": "Satori Maiden ~ 3rd eye",
    "th11_10": "Lullaby of Deserted Hell",
    "th11_11": "Corpse Voyage ~ Be of good cheer!",
    "th11_12": "Hellfire Mantle",
    "th11_13": "Solar Sect of Mystic Wisdom ~ Nuclear Fusion",
    "th11_14": "Last Remote",
    "th11_15": "Hartmann's Youkai Girl",
    "th11_16": "The Earth Spirits' Homecoming",
    "th11_17": "Energy Daybreak ~ Future Dream...",
    "th12_01": "A Shadow in the Blue Sky",
    "th12_02": "At the End of Spring",
    "th12_03": "A Tiny, Tiny, Clever Commander",
    "th12_04": "The Sealed Cloud Route",
    "th12_05": "Beware the Umbrella Left There Forever",
    "th12_06": "Sky Ruin",
    "th12_07": "The Traditional Old Man and the Stylish Girl",
    "th12_08": "Interdimensional Voyage of a Ghostly Passenger Ship",
    "th12_09": "Captain Murasa",
    "th12_10": "Rural Makai City Esoteria",
    "th12_11": "The Tiger-Patterned Bishamonten",
    "th12_12": "Fires of Hokkai",
    "th12_13": "Emotional Skyscraper ~ Cosmic Mind",
    "th12_14": "UFO Romance in the Night Sky",
    "th12_15": "Heian Alien",
    "th12_16": "Youkai Temple",
    "th12_17": "Returning Home From the Sky ~ Sky Dream",
    "th125_01": "Newshound",
    "th125_02": "The Mystery in Your Town",
    "th125_03": "Youkai Modern Colony",
    "th125_04": "Nemesis' Stronghold",
    "th125_05": "Bell of Avici ~ Infinite Nightmare",
    "th125_06": "Youkai Mountain ~ Mysterious Mountain",
    "th128_01": "An Ice Fairy in Spring",
    "th128_02": "The Refrain of the Lovely Great War",
    "th128_03": "Staking Your Life on a Prank",
    "th128_04": "Year-Round Absorbed Curiosity",
    "th128_05": "A Midnight Fairy Dance",
    "th128_06": "Great Fairy Wars ~ Fairy Wars",
    "th128_07": "Loose Rain",
    "th128_08": "Magus Night",
    "th128_09": "An Ice Fairy in Spring - still -",
    "th128_10": "Player's Score",
    "th13_01": "Spirit of Avarice",
    "th13_02": "Night Sakura of Dead Spirits",
    "th13_03": "Ghost Lead",
    "th13_04": "Welcome to Youkai Temple",
    "th13_05": "Youkai Girl at the Gate",
    "th13_06": "Let's Live in a Lovely Cemetery",
    "th13_07": "Rigid Paradise",
    "th13_08": "Desire Drive",
    "th13_09": "Old Yuanxian",
    "th13_10": "The Hall of Dreams' Great Mausoleum",
    "th13_11": "Legend of the Great Gods",
    "th13_12": "Starry Sky of Small Desires",
    "th13_13": "Shoutoku Legend ~ True Administrator",
    "th13_14": "Youkai Back Shrine Road",
    "th13_15": "Futatsuiwa from Sado",
    "th13_16": "A New Wind at the Shrine",
    "th13_17": "Desire Dream",
    "th14_01": "Mysterious Purification Rod",
    "th14_02": "Mist Lake",
    "th14_03": "Mermaid from the Uncharted Land",
    "th14_04": "Humans and Youkai Traversing the Canal",
    "th14_05": "Dullahan Under the Willows",
    "th14_06": "Bamboo Forest of the Full Moon",
    "th14_07": "Lonesome Werewolf",
    "th14_08": "Magical Storm",
    "th14_09": "Illusionary Jōruri",
    "th14_10": "The Shining Needle Castle Sinking in the Air",
    "th14_11": "Reverse Ideology",
    "th14_12": "The Exaggerated Castle Keep",
    "th14_13": "Inchlings of the Shining Needle ~ Little Princess",
    "th14_14": "Thunderclouds of Magical Power",
    "th14_15": "Primordial Beat ~ Pristine Beat",
    "th14_16": "Magical Power of the Mallet",
    "th14_17": "Strange, Strange Instruments",
    "th143_01": "Raise the Flag of Cheating",
    "th143_02": "Cheat Against Impossible Danmaku",
    "th143_03": "Midnight Spell Card",
    "th143_04": "Romantic Escape Flight",
    "th143_05": "Eternal Transient Reign",
    "th143_06": "Mermaid from the Uncharted Land",
    "th143_07": "Reverse Ideology",
    "th143_08": "Illusionary Jōruri",
    "th143_09": "Youkai Mountain ~ Mysterious Mountain"
}