Usage: thanm COMMAND
COMMAND can be:
  l[OPTION...] ARCHIVE            list archive
  x[OPTION...] ARCHIVE [FILE...]  extract entries
  r[OPTION...] ARCHIVE NAME FILE  replace entry in archive
  c[OPTION...] ARCHIVE SPEC       create archive
  V                               display version information and exit
OPTION can be:
  f  ignore errors when possible
Report bugs to <mpp.translation@gmail.com / xarnonymous@gmail.com>.
