{
    "common-0": "\"Temperament Manifestation\"",
    "common-1": "\"Bomb\"",
    "common-2": "\"Guard Reversal\"",
    "common-3": "\"Spell Amplifier\"",
    "common-4": "\"Life Regenerator\"",
    "common-5": "\"Spirit Regenerator\"",
    "reimu-0": "Prayer \"Disaster-Dispelling Prayer\"",
    "reimu-4": "Treasure Sign \"Dancing Yin-Yang Orbs\"",
    "reimu-8": "Dream Land \"Super Duplex Barrier\"",
    "reimu-12": "Light Spirit \"Divine Spirit Orbs\"",
    "reimu-16": "\"Lurking Boundary Spirits and the Mysterious Shrine Maiden\"",
    "reimu-100": "Hakurei Amulet",
    "reimu-101": "Cautionary Border",
    "reimu-102": "Dimensional Rift",
    "reimu-103": "Ascension Kick",
    "reimu-104": "Youkai Buster",
    "reimu-105": "Binding Border",
    "reimu-106": "Demon-Sealing Dimensional Rift",
    "reimu-107": "Sliding Ascension Kick",
    "reimu-108": "Spread Amulet",
    "reimu-109": "Permanent Border",
    "reimu-110": "Instant Dimensional Rift",
    "reimu-200": "Spirit Sign \"Fantasy Orb\"",
    "reimu-201": "Divine Spirit \"Fantasy Seal\"",
    "reimu-206": "Divine Arts \"Omnidirectional Demon-Binding Circle\"",
    "reimu-208": "Jewel Sign \"Orbs of Light, Cast into Shade\"",
    "reimu-209": "Treasure Sign \"Yin-Yang Treasured Orb\"",
    "reimu-210": "Holy Relic \"Yin-Yang Demon God Orb\"",
    "reimu-214": "Divine Arts \"Sky-Conquering Wind God Kick\"",
    "reimu-219": "\"Fantasy Nature\"",
    "marisa-0": "Star Sign \"Polaris Unique\"",
    "marisa-4": "Armillary \"Orreries Universe\"",
    "marisa-8": "Perverse Love \"Easy-Harvest Master Spark\"",
    "marisa-100": "Witch Leyline",
    "marisa-101": "Miasma Sweep",
    "marisa-102": "Ground Stardust",
    "marisa-103": "Meteonic Debris",
    "marisa-104": "Radial Strike",
    "marisa-105": "Bosky Sweeper",
    "marisa-106": "Devildom Torch",
    "marisa-107": "Narrow Spark",
    "marisa-108": "Up Sweep",
    "marisa-109": "Stellar Missile",
    "marisa-111": "Green Spread",
    "marisa-200": "Love Sign \"Master Spark\"",
    "marisa-202": "Magicannon \"Final Spark\"",
    "marisa-203": "Star Sign \"Dragon Meteor\"",
    "marisa-205": "Magic Sign \"Stardust Reverie\"",
    "marisa-206": "Star Sign \"Escape Velocity\"",
    "marisa-207": "Comet \"Blazing Star\"",
    "marisa-208": "Star Sign \"Meteonic Shower\"",
    "marisa-211": "Light Sign \"Luminous Strike\"",
    "marisa-215": "Ritual Sign \"Orreries Sun\"",
    "sakuya-0": "Silver Sign \"Silver Bound\"",
    "sakuya-4": "Time Sign \"Sakuya's Special Stopwatch\"",
    "sakuya-8": "Illusion \"My Knife's Recursions\"",
    "sakuya-12": "Time Sign \"Silver Acute 360\"",
    "sakuya-100": "Close-up Magic",
    "sakuya-101": "Bounce/No-Bounce",
    "sakuya-102": "Magic Star Sword",
    "sakuya-103": "Vanishing Everything",
    "sakuya-104": "Propelling Silver",
    "sakuya-105": "Square Ricochet",
    "sakuya-106": "Sight of Distant Blade",
    "sakuya-107": "Perfect Maid",
    "sakuya-200": "Illusion Sign \"Killer Doll\"",
    "sakuya-201": "Time Sign \"Private Square\"",
    "sakuya-202": "Wound Sign \"Inscribe Red Soul\"",
    "sakuya-203": "Buriallusion \"Phantomic Killer in Night Mist\"",
    "sakuya-204": "\"Sakuya's World\"",
    "sakuya-205": "Scarred Soul \"Soul Sculpture\"",
    "sakuya-207": "Conjuring \"Eternal Meek\"",
    "sakuya-208": "Speed Sign \"Luminous Ricochet\"",
    "alice-0": "Trooper \"Suicide Squad\"",
    "alice-4": "Sword Sign \"Soldier of Cross\"",
    "alice-8": "Doll \"Soulless Folk Dance\"",
    "alice-100": "Doll Placement",
    "alice-101": "Doll Negation",
    "alice-102": "Doll Arrangment",
    "alice-103": "Doll Activation",
    "alice-104": "Returning Dolls",
    "alice-105": "Doll Cremation",
    "alice-106": "Thousand Spear Dolls",
    "alice-107": "SP Doll",
    "alice-109": "Ooedo Explosive Marionette",
    "alice-111": "Seeker Wire",
    "alice-200": "Magic Sign \"Artful Sacrifice\"",
    "alice-201": "War Sign \"Little Legion\"",
    "alice-202": "Curse Sign \"Shanghai Doll\"",
    "alice-203": "Magipulation \"Return Inanimateness\"",
    "alice-204": "War Command \"Doll's War\"",
    "alice-205": "Curse \"Hourai Doll\"",
    "alice-206": "Spy Sign \"Seeker Dolls\"",
    "alice-207": "Crimson Sign \"Holland Doll\"",
    "alice-208": "Doll \"Futuristic Bunraku\"",
    "alice-209": "Focus Power \"Trip Wire\"",
    "patchouli-0": "Fire Sign \"Akiba Summer\"",
    "patchouli-4": "Water Sign \"Jelly Fish Princess\"",
    "patchouli-8": "Moon Metal Sign \"Sunshine Reflector\"",
    "patchouli-100": "Summer Red",
    "patchouli-101": "Winter Element",
    "patchouli-102": "Spring Wind",
    "patchouli-103": "Autumn Edge",
    "patchouli-104": "Doyou Spear",
    "patchouli-105": "Summer Flame",
    "patchouli-106": "Condensed Bubble",
    "patchouli-107": "Flash of Spring",
    "patchouli-108": "Autumn Blade",
    "patchouli-109": "Emerald City",
    "patchouli-200": "Fire Metal Sign \"Saint Elmo's Pillar\"",
    "patchouli-201": "Earth Water Sign \"Noachian Deluge\"",
    "patchouli-202": "Metal Wood Sign \"Elemental Harvester\"",
    "patchouli-203": "Sun Sign \"Royal Flare\"",
    "patchouli-204": "Moon Sign \"Silent Selene\"",
    "patchouli-205": "Fire Water Wood Metal Earth Sign \"Philosopher's Stone\"",
    "patchouli-207": "Moon & Wood Sign \"Satellite Himawari\"",
    "patchouli-210": "Sun Wood Sign \"Photosynthesis\"",
    "youmu-0": "Human Knowledge Sword \"Turning Angel Cut\"",
    "youmu-4": "Cherry Blossom Sword \"Flashing Scattered Flowers\"",
    "youmu-8": "Thought-Cutting Sword \"Slash of the Buddhahood of Flora\"",
    "youmu-12": "Closed-Eye Slash \"The Bullet-Cutting Spirit Eye from Roukan\"",
    "youmu-100": "Lower Realm Reflection Slash",
    "youmu-101": "Crescent Moon Slash",
    "youmu-102": "Transmigration Slash",
    "youmu-103": "Spirit Medium's Bind",
    "youmu-104": "Lotus Posture Slash",
    "youmu-105": "Preaching Avici",
    "youmu-106": "Heart Excerpt Slash",
    "youmu-107": "Wicked Soul",
    "youmu-109": "Insightful Sword",
    "youmu-111": "Strange Half-Body",
    "youmu-200": "Human Sign \"Slash of Present World\"",
    "youmu-201": "Life-Cutting Sword \"Slash of Meditation\"",
    "youmu-202": "Soul Sign \"Wheel of Pain of the Living and Dead\"",
    "youmu-203": "Human Oni \"Slash of the Eternal Future\"",
    "youmu-204": "Hesitation-Cutting Sword \"Slash of Departing from Hesitation\"",
    "youmu-205": "Konpaku \"Dharma of Gumonji Wisdom of the Living and Dead\"",
    "youmu-206": "Sword Skill \"Cherry Blossom Flashing\"",
    "youmu-207": "Spirit-Cutting Sword \"Slash of Ascension to Buddhahood\"",
    "remilia-0": "Destiny \"Miserable Fate\"",
    "remilia-4": "Night Sign \"Bombard Night\"",
    "remilia-8": "Bat \"Vampire Sweep\"",
    "remilia-12": "God Devil \"Remilia Stoker\"",
    "remilia-100": "Demon Lord Walk",
    "remilia-101": "Servant Flier",
    "remilia-102": "Demon Lord Cradle",
    "remilia-103": "Demon Lord Arrow",
    "remilia-104": "Vampire Claw",
    "remilia-105": "Chain Gang",
    "remilia-106": "Rocket Kick Upper",
    "remilia-107": "Ceiling Fear",
    "remilia-109": "Demon's Dinner Fork",
    "remilia-200": "Scarlet Sign \"Red the Nightless Castle\"",
    "remilia-201": "Certain Kill \"Heart Break\"",
    "remilia-202": "Night Sign \"Demon King Cradle\"",
    "remilia-203": "Scarlet Devil \"Scarlet Devil\"",
    "remilia-204": "Divine Spear \"Spear the Gungnir\"",
    "remilia-205": "Night Lord \"Dracula Cradle\"",
    "remilia-206": "Night Sign \"Bad Lady Scramble\"",
    "yuyuko-0": "Ghostly Sign \"Netherworld Mystery Spot\"",
    "yuyuko-4": "Spirit Butterfly \"In the Moment Where a Butterfly's Wings Flap\"",
    "yuyuko-8": "Banquet \"All Things Come Full Circle in Death\"",
    "yuyuko-100": "Ghostly Butterfly",
    "yuyuko-101": "Light of the Unborn",
    "yuyuko-102": "All Things Wandering",
    "yuyuko-103": "Dance of Dreaming Butterfly",
    "yuyuko-104": "Spirits that Died Well",
    "yuyuko-105": "Lance of the Swallowtail Crest",
    "yuyuko-106": "Spirit-Luring Nectar",
    "yuyuko-107": "Reverse Screens",
    "yuyuko-108": "Sphere Bloom",
    "yuyuko-200": "Death Sign \"Ghastly Dream\"",
    "yuyuko-201": "Nether Sign \"Path to Yomotsu-Hirasaka\"",
    "yuyuko-202": "Spirit Sign \"Ageless Dream\"",
    "yuyuko-203": "Deadly Butterfly \"Eternal Sleep in Dreamland\"",
    "yuyuko-204": "Lost Again \"Gensokyo's Rise from Yomi\"",
    "yuyuko-205": "Lifespan \"Ticket to the Ageless Land\"",
    "yuyuko-207": "Butterfly Sign \"Deadly Lance of the Swallowtail Butterfly Crest\"",
    "yuyuko-208": "Ghostly Elegance \"Light Trap of Passing Away\"",
    "yukari-0": "Photon \"Doppler Effect\"",
    "yukari-4": "Splitter \"Thing That Splits All Into Two\"",
    "yukari-8": "Fantasy Nest \"Flying Glow Worm's Nest\"",
    "yukari-12": "Aerial Bait \"Hyperactive High Speed Flying Object\"",
    "yukari-16": "\"Yakumo's Nest\"",
    "suika-0": "Breath \"Small Oni's Deep Breath\"",
    "suika-4": "Fireball \"Earth Spirit Reactive Bullet\"",
    "suika-8": "Oni Sign \"Missing Purple Power\"",
    "suika-12": "Qi of Oni \"Deep Fog Labyrinth\"",
    "suika-16": "\"A Million Oni in One\"",
    "suika-100": "Spectre -Dense-",
    "suika-101": "Gnome -Dense-",
    "suika-102": "Spectre -Sparse-",
    "suika-103": "Gathering Oni",
    "suika-104": "Oni Spirit Bomb",
    "suika-105": "Gnome -Sparse-",
    "suika-106": "Unpleasant Mist",
    "suika-107": "Thin Oni",
    "suika-109": "Fire Oni",
    "suika-200": "Gather Sign \"Throwing Mt.Togakushi\"",
    "suika-201": "Drunk Sign \"Art of Oni Binding\"",
    "suika-202": "Oni Sign \"Missing Power\"",
    "suika-203": "Gathering Oni \"Throwing Ame-no-Tajikarao\"",
    "suika-204": "Drunken Dream \"Art of Segaki Binding\"",
    "suika-206": "Mist Sign \"Gathering and Dissipating\"",
    "suika-207": "Will-o'-Wisp \"Super High Density Phosphorus Disaster Art\"",
    "suika-208": "Oni Sign \"Complete Massacre on Mt. Ooe\"",
    "reisen-0": "Force Sign \"Menacing Hallucination (Obsessioner)\"",
    "reisen-4": "Illusion Bullet \"Illusion Parallax (Bluff Barrage)\"",
    "reisen-8": "Illusion Rabbit \"Concurrent Crossing (Parallel Cross)\"",
    "reisen-100": "Mind Explosion",
    "reisen-101": "Illusionary Blast",
    "reisen-102": "Ultrared Field",
    "reisen-103": "Disbelief Aspect",
    "reisen-104": "Mind Bending",
    "reisen-105": "Eyesight Cleaning",
    "reisen-106": "Ultraviolet Field",
    "reisen-107": "Disorder Eye",
    "reisen-108": "Mind Dropping",
    "reisen-109": "Ripple Vision",
    "reisen-110": "Undersense Break",
    "reisen-200": "Charming Look \"Disjointed Circular Corolla (Corolla Vision)\"",
    "reisen-202": "Illusion Bomb \"Myopic Firework (Mind Starmine)\"",
    "reisen-203": "Fascination \"Corolla Glance (Crown Vision)\"",
    "reisen-205": "\"Stare of the Hazy Phantom Moon (Lunatic Red Eyes)\"",
    "reisen-206": "Weak Heart \"Empty Heart, Empty Mind (Demotivation)\"",
    "reisen-207": "Empty Heart \"Scars of an Empty Heart (Discarder)\"",
    "reisen-208": "Poison Smokescreen \"Orb of Gas-Treated Weave\"",
    "reisen-209": "Life Elixir \"Peerless Patriot's Elixir\"",
    "aya-0": "Squall \"Sarutahiko's Guidance\"",
    "aya-4": "Whirl Sign \"Fluttering Strange Fan\"",
    "aya-8": "Recollection \"Torii Whorl-Wind\"",
    "aya-12": "\"Illusionary Dominance\"",
    "aya-100": "Gust Fan",
    "aya-101": "Domination Dash",
    "aya-102": "Tengu's Mist Standing",
    "aya-103": "Pelting in the Night",
    "aya-104": "Gale Fan",
    "aya-105": "Graceful Dash",
    "aya-106": "Tengu's Downburst",
    "aya-107": "Wind Sickle Veiling",
    "aya-109": "Tengu Tree-Felling",
    "aya-110": "Tengu's Drumbeats",
    "aya-200": "Whirl Sign \"Maple Leaf Fan\"",
    "aya-201": "Tornado \"Guidepost for the Advent of the Divine Grandson\"",
    "aya-202": "Headwind \"Route Forbidden to Man\"",
    "aya-203": "Thrust Sign \"Tengu's Macroburst\"",
    "aya-205": "Wind Sign \"Opening Wind of the Tengu Realm\"",
    "aya-211": "Demon Beast \"Sickle Weasel Veiling\"",
    "komachi-0": "Spirit Sign \"Awakening of the Ancient Earthbound Spirits\"",
    "komachi-4": "Soul Sign \"Scythe of Roaming Spirits\"",
    "komachi-8": "Soul Sign \"Game of the Soul\"",
    "komachi-100": "Human Spirits who Lived Without Hesitance",
    "komachi-101": "Earthbound Spirits who Find No Rest",
    "komachi-102": "Ritual of Ecstasy",
    "komachi-103": "Floating Spirits who Lived Indolently",
    "komachi-104": "Scythe of the Reaper",
    "komachi-105": "Wind on the Last Journey",
    "komachi-106": "Way of Avici",
    "komachi-107": "Lonely Bound Spirit",
    "komachi-108": "Human Spirit Passing By",
    "komachi-110": "Last Farewell: Trial Edition",
    "komachi-200": "Boat Sign \"Flow of the River\"",
    "komachi-201": "Poor Fate \"Your Days Are Numbered\"",
    "komachi-202": "Spirit Sign \"Abundant Wandering Spirits\"",
    "komachi-203": "Death Song \"Ferry of the Deep Fog\"",
    "komachi-204": "Exchange \"Unvalued Life, Valued Life\"",
    "komachi-205": "Malice Sign \"Regretful Bound Spirits\"",
    "komachi-211": "Hell \"Narrow Confines of Avici\"",
    "iku-0": "Light Orb \"Dragon's Gleaming Eyes\"",
    "iku-4": "Thunder Sign \"Residence of the Thunder God\"",
    "iku-8": "Thorn Sign \"Thundercloud Stickleback\"",
    "iku-12": "Cloud Realm \"The Thunder Court in the Sea of Abstruse Clouds\"",
    "iku-100": "Dragon Fish's Strike",
    "iku-101": "Veils like Water",
    "iku-102": "Dragon Fish's Wrath",
    "iku-103": "Electrostatic Guided Missile",
    "iku-104": "Dragon God's Strike",
    "iku-105": "Veils like Wind",
    "iku-106": "Dragon God's Wrath",
    "iku-107": "Dragon God's Lightning Flash",
    "iku-111": "Dragon's Eye",
    "iku-200": "Electric Sign \"Thunder Drum Shot\"",
    "iku-201": "Fish Sign \"Dragonfish Drill\"",
    "iku-202": "Lightning Sign \"Elekiter Dragon Palace\"",
    "iku-203": "Star Light \"Light Dragon's Sigh\"",
    "iku-206": "Lightning Fish \"Swimming Thunder Shot\"",
    "iku-207": "Angel's Raiment \"Veils Like Sky\"",
    "iku-210": "Dragon Fish \"Dragon Palace Messenger's Swimming Shot\"",
    "tenshi-0": "Keystone \"Sky's Spiritual Stone\"",
    "tenshi-4": "Qian & Kun \"Violent Land that Mothers All\"",
    "tenshi-8": "Spirit Thought \"Stone that Calms the Lands\"",
    "tenshi-12": "Heaven & Earth \"Land that Oversees the Distant World Below\"",
    "tenshi-16": "\"Sky of Scarlet Perception of All Mankind\"",
    "tenshi-100": "Sword of Kun",
    "tenshi-101": "Pillars of Divine Punishment",
    "tenshi-102": "Beams of Non-Perception",
    "tenshi-103": "Sword of Non-Perception",
    "tenshi-104": "Six Earthquakes -Signs-",
    "tenshi-105": "Guarding Keystones",
    "tenshi-106": "Heaven and Earth Press",
    "tenshi-107": "Sword of Non-Perception",
    "tenshi-200": "Earth Sign \"Sword of Unletting Soil\"",
    "tenshi-201": "Non-Perception \"Sword of Neither Perception nor Non-Perception\"",
    "tenshi-202": "Heaven Sign \"Sword of Divine Justice\"",
    "tenshi-203": "Earthquake \"Sword of Pleasure After Hardship\"",
    "tenshi-204": "Spirit Sign \"Sword of Meteorological Revelation\"",
    "tenshi-205": "Keystone \"World Creation Press\"",
    "tenshi-206": "Spirit Sign \"State of Freedom from Worldly Thoughts\"",
    "yukari-204": "Shikigami \"Chen\"",
    "yukari-215": "Abandoned Line \"Aimless Journey to the Abandoned Station\"",
    "yukari-207": "Aerial Bait \"Addictive Bait\"",
    "yukari-205": "Barrier \"Objective Barrier\"",
    "yukari-203": "Barrier \"Charming Quadruple Barrier\"",
    "yukari-201": "Shikigami \"Ran Yakumo\"",
    "yukari-202": "Border Sign \"Boundary of 2D and 3D\"",
    "yukari-200": "Border Sign \"Quadruple Barrier\"",
    "yukari-107": "Flesh Dismantler",
    "yukari-108": "Bewitching Bait",
    "yukari-106": "Universe of Matter and Antimatter",
    "yukari-105": "Fantasy Manji-Parasol",
    "yukari-104": "Home is Where One Lays One's Head",
    "yukari-103": "Fantasy Maniacal Rift",
    "yukari-100": "Urashima's Box, Filled With Lament",
    "yukari-102": "Rest on Stone, Rinse in Rivers",
    "yukari-101": "Bewitching Butterfly in the Zen Temple"
}