{
    "77": "Imitation \"Milky Way\"",
    "78": "Imitation \"Milky Way\"",
    "79": "Malice Sign \"Meteorite Shower\"",
    "80": "Malice Sign \"Meteorite Shower\"",
    "81": "Imitation \"Stardust Reverie\"",
    "82": "Imitation \"Stardust Reverie\"",
    "83": "Heavenly Power \"Starstruck\"",
    "84": "Heavenly Power \"Starstruck\"",
    "85": "Malice Sign \"Blinding Laser\"",
    "86": "Malice Sign \"Blinding Laser\"",
    "87": "Evil Spirit \"Scatterlight\"",
    "88": "Evil Spirit \"Scatterlight\"",
    "89": "Malice Sign \"Light of Dawn\"",
    "90": "Malice Sign \"Light of Dawn\"",
    "91": "Demonic Sign \"Twin Suns\"",
    "92": "Demonic Sign \"Twin Suns\"",
    "93": "Imitation \"Earthlight Ray\"",
    "94": "Imitation \"Earthlight Ray\"",
    "95": "Ghost \"Beams of Wisdom\"",
    "96": "Ghost \"Beams of Wisdom\"",
    "97": "Ultimate Power \"Twilight Spark\"",
    "98": "Ultimate Power \"Twilight Spark\"",
    "99": "Ultimate Power \"Spark of the Universe\"",
    "215": "\"Blazing Comet\""
}
