{
    "0": "Horror \"Tsurube-Otoshi Apparition\"",
    "2": "Trap Sign \"Capture Web\"",
    "4": "Spider \"Cave Spider's Nest\"",
    "6": "Miasma Sign \"Filled Miasma\"",
    "8": "Miasma \"Unexplained Fever\"",
    "10": "Jealousy Sign \"Green-Eyed Monster\"",
    "12": "Envy \"Green-Eyed Invisible Monster\"",
    "14": "Grandpa Hanasaka \"Jealousy of the Kind & Lovely\"",
    "16": "Grandpa Hanasaka \"Shiro's Ashes\"",
    "18": "Tongue-Cut Sparrow \"Hate for the Humble & Rich\"",
    "20": "Tongue-Cut Sparrow \"Large Box & Small Box\"",
    "22": "Malice Sign \"Shrine Visit in the Dead of Night\"",
    "24": "Malice Sign \"Day 7 of the Shrine Visits in the Dead of Night\"",
    "26": "Oni Sign \"Anomalies, Strength, Disorder, & Spirits\"",
    "30": "Mysterious Ring \"Hell's Wheel of Pain\"",
    "32": "Shackles Sign \"Shackles a Criminal Can't Take Off\"",
    "34": "Feat of Strength \"Storm on Mt. Ooe\"",
    "36": "Feat of Strength \"Wind Blowing Down from Mt. Ooe\"",
    "38": "Big Four Arcanum \"Knock Out In Three Steps\"",
    "40": "Big Four Arcanum \"Knock Out In Three Steps\"",
    "42": "Recollection \"Terrible Souvenir\"",
    "44": "Recollection \"Terrifying Hypnotism\"",
    "46": "Recollection \"Double Black Death Butterfly\"",
    "50": "Recollection \"Flying Insect's Nest\"",
    "54": "Recollection \"Border of Wave & Particle\"",
    "58": "Recollection \"Throwing Mt. Togakushi\"",
    "62": "Recollection \"Pandemonium\"",
    "66": "Recollection \"Deep Mist Labyrinth\"",
    "70": "Recollection \"Wind God Hidden Among Tree Leaves\"",
    "74": "Recollection \"Tengu's Macroburst\"",
    "78": "Recollection \"Torii Whirlwind\"",
    "82": "Vague Recollection \"Disintegrating Particle Formation\"",
    "86": "Vague Recollection \"Berserk Robot Kamikaze\"",
    "90": "Vague Recollection \"Self-Destructing Android Fairies\"",
    "94": "Vague Recollection \"Fiery Shackles, Red Spear\"",
    "98": "Vague Recollection \"Magical Rain, Violet Tracks\"",
    "102": "Copycat \"Myriad of Madness\"",
    "106": "Vague Recollection \"Wild Aurora\"",
    "110": "Recollection \"Meteorite Shower\"",
    "114": "Recollection \"Asteroid Belt -Prototype-\""
}
