{
    "common-0": "\"Spiritual Strike Talisman\"",
    "common-20": "\"Catfish's Great Earthquake\"",
    "common-19": "\"Three Heavenly Drops\"",
    "common-18": "\"Control Rod\"",
    "common-16": "\"Frozen Frog\"",
    "common-17": "\"Dragon Star\"",
    "common-15": "\"Illness Recovery Charm\"",
    "common-14": "\"Sword of Scarlet Perception\"",
    "common-13": "\"Divine Raiment of the Dragon Fish\"",
    "common-11": "\"Spell-Breaking Drug\"",
    "common-10": "\"Tengu Fan\"",
    "common-12": "\"Yesterday's Money\"",
    "common-9": "\"Ibuki Gourd\"",
    "common-7": "\"Soul Torch\"",
    "common-8": "\"Left-Handed Folding Fan\"",
    "common-6": "\"Custom Parasol\"",
    "common-5": "\"Grimoire\"",
    "common-3": "\"Hakurouken\"",
    "common-2": "\"Stopwatch\"",
    "common-4": "\"Sacrificial Doll\"",
    "common-1": "\"Magic Potion\"",
    "reimu-0": "Amulet \"Youkai Repelling Charm\"",
    "reimu-4": "Spirit Sign \"Fantasy Seal -Circle-\"",
    "reimu-8": "Divine Spirit \"Fantasy Seal -Blink-\"",
    "reimu-12": "\"Most Evil Surprise Miko Orbs\"",
    "reimu-207": "Barrier \"Expanding Barrier\"",
    "reimu-204": "Dream Sign \"Evil-Sealing Circle\"",
    "reimu-111": "Rain Dance",
    "marisa-219": "Perverse Love \"Easy-Harvest Master Spark\"",
    "marisa-212": "Light Sign \"Earthlight Ray\"",
    "marisa-204": "Love Sign \"Non-Directional Laser\"",
    "marisa-4": "Light Flow \"Shooting Echo\"",
    "marisa-0": "Star Sign \"Eccentric Asteroid\"",
    "marisa-110": "Magical Waste-Recycling Bomb",
    "marisa-8": "Magic Sign \"Magical R360\"",
    "marisa-209": "Star Sign \"Gravity Beat\"",
    "marisa-214": "Magic Waste \"Deep Ecological Bomb\"",
    "sakuya-209": "Time Sign \"Sakuya's Special Stopwatch\"",
    "sakuya-206": "Silver Sign \"Silver Bound\"",
    "sakuya-109": "Misdirection",
    "sakuya-108": "Dancing Star Sword",
    "sakuya-110": "Parallel Brane",
    "sakuya-111": "Time Paradox",
    "sakuya-210": "Light Speed \"C. Ricochet\"",
    "sakuya-211": "Time Sign \"Imaginary Vertical Time\"",
    "sakuya-212": "Watch \"Lunar Dial\"",
    "alice-211": "Dolls \"Lemmings' Parade\"",
    "alice-110": "Doll Archers",
    "alice-210": "Lance Sign \"Cutie Phalanx\"",
    "alice-8": "Sacrifice \"Suicide Pact\"",
    "alice-108": "Doll Ambush",
    "alice-16": "Testing \"Goliath Doll\"",
    "alice-12": "Testing \"Level Titania\"",
    "alice-4": "Knight \"Doll of Round Table\"",
    "alice-0": "Doll \"Semi-Automaton\"",
    "patchouli-4": "Water Sign \"Princess Undine\"",
    "patchouli-0": "Fire Sign \"Ring of Agni\"",
    "patchouli-206": "Water Sign \"Jelly Fish Princess\"",
    "patchouli-213": "Sun & Moon Sign \"Royal Diamond Ring\"",
    "patchouli-212": "Earth & Metal Sign \"Emerald Megalith\"",
    "patchouli-211": "Fire Water Sign \"Phlogistic Pillar\"",
    "patchouli-114": "Diamond Hardness",
    "patchouli-112": "Static Green",
    "patchouli-113": "Fall Slasher",
    "patchouli-111": "Sticky Bubbles",
    "patchouli-110": "Wipe Moisture",
    "remilia-111": "Stigmanizer",
    "remilia-110": "Vampire Kiss",
    "remilia-108": "Trickster Devil",
    "youmu-208": "Voidness Sword \"Slash Clearing the Six Senses\"",
    "youmu-110": "Slashing a Flower Upon One's Head",
    "youmu-212": "Reincarnation Sword \"Slash of Circular Vicissitude\"",
    "youmu-108": "Phosphoric Slash",
    "remilia-209": "Devil \"Remilia Stretch\"",
    "remilia-208": "\"Millennium Vampire\"",
    "remilia-207": "Destiny \"Miserable Fate\"",
    "yuyuko-111": "Sense of Elegance",
    "yuyuko-109": "Land of Death",
    "yuyuko-110": "Gifts to the Deceased",
    "yuyuko-219": "\"Resurrection Butterfly\"",
    "yuyuko-209": "Cherry Blossom Sign \"Sense of Cherry Blossom\"",
    "yuyuko-206": "Spirit Butterfly \"In the Moment Where a Butterfly's Wings Flap\"",
    "yukari-111": "Chimera Wings",
    "yukari-110": "Eyes that View Change",
    "yukari-109": "Boundary of Intellect and Feet",
    "yukari-208": "Magic Eye \"Laplace's Demon\"",
    "yukari-206": "Fantasy Nest \"Flying Glow Worm's Nest\"",
    "suika-212": "Big Four Arcanum \"Knock Out In Three Steps\"",
    "suika-205": "Oni God \"Missing Purple Power\"",
    "suika-110": "Oni God's Will-o'-Wisp Art",
    "suika-111": "Kidnapping Oni",
    "suika-108": "Foot Bellows",
    "reisen-211": "Farsight \" Infrared Moon (In the Red Moonlight)\"",
    "reisen-204": "Red Eye \" Lunatic Blast (Viewing the Circle Moon)\"",
    "reisen-111": "Ocular Spectrum",
    "reisen-210": "Shortsight \" X-Wave (Ultrashort Brainwave)\"",
    "aya-212": "Squall \"Sarutahiko's Guidance\"",
    "aya-208": "Crow Sign \"Daymare in the Dark Night\"",
    "aya-207": "Wind Sign \"Tengu Newspaper Deadline Day\"",
    "aya-111": "Tengu's Gravel",
    "aya-206": "\"Illusionary Dominance\"",
    "aya-108": "Maple Fan's Wind",
    "komachi-207": "Soul Sign \"Scythe of Roaming Spirits\"",
    "komachi-206": "Death Sign \"Scythe of Final Judgement\"",
    "komachi-111": "Spirit-Detaching Scythe",
    "komachi-109": "Sanzu Boat",
    "iku-110": "Whiskers of the Dragon God",
    "iku-109": "Celestial Maiden's Strike",
    "iku-108": "Able-Swimming Dragon Fish",
    "iku-211": "Orb Sign \"Orb of the Five-Clawed Dragon\"",
    "iku-209": "Thorn Sign \"Thundercloud Stickleback\"",
    "iku-208": "Angel's Raiment \"Veils Like Time\"",
    "tenshi-111": "Ascension Thrust",
    "tenshi-108": "Sword of Karma",
    "tenshi-110": "Scarlet Sword Temperament",
    "tenshi-109": "Awakening of the Earth Spirits",
    "tenshi-207": "\"Sky of Scarlet Perception of All Mankind\"",
    "tenshi-209": "Weather \"Scarlet Weather Stimulation\"",
    "tenshi-208": "Sword Skill \"Sword of Ebullience\"",
    "sanae-101": "Omikuji Bomb",
    "sanae-100": "Wind Calling",
    "sanae-0": "Snake Sign \"Great Snake Swimming in the Clouds\"",
    "sanae-4": "Miracle \"Miracle of Fafrotskies\"",
    "sanae-103": "Earth-God Summon: Shield",
    "sanae-102": "Sky-God Summon: Thrust",
    "sanae-210": "Esoterica \"Nine Syllable Stabs\"",
    "sanae-205": "Sea Opening \"Moses's Miracle\"",
    "sanae-207": "Miracle \"Night with Overly Bright Guest Stars\"",
    "sanae-200": "Prayer \"Charm of Good Commerce\"",
    "sanae-201": "Esoterica \"Gray Thaumaturgy\"",
    "sanae-206": "Miracle \"Daytime Guest Stars\"",
    "sanae-204": "Sea Opening \"The Day the Sea Split\"",
    "sanae-203": "Omikuji \"Random Omikuji Barrage\"",
    "sanae-202": "Esoterica \"Forgotten Ritual\"",
    "sanae-111": "Earth-God Summon: Shield",
    "sanae-110": "Sky-God Summon: Onbashira",
    "sanae-109": "Cobalt Spread",
    "sanae-108": "Star Falling",
    "sanae-105": "Sky Serpent",
    "sanae-106": "Sky-God Summon: Wind",
    "sanae-107": "Earth-God Summon: Iron Ring",
    "sanae-104": "Wave Calling",
    "cirno-4": "Freeze Sign \"Minus K\"",
    "cirno-0": "Ice Sign \"Icicle Fall\"",
    "meiling-0": "Colorful Flip \"Fluttering Petals and Falling Leaves\"",
    "meiling-4": "Colorful Sign \"Extreme Color Typhoon\"",
    "cirno-204": "Freeze Sign \"Perfect Freeze\"",
    "cirno-201": "Frost Sign \"Frost Columns\"",
    "cirno-200": "Ice Sign \"Icicle Machine Gun\"",
    "cirno-213": "Cold Sign \"Insta-Freeze Beam\"",
    "cirno-210": "Freeze Sign \"Freeze Atmosphere\"",
    "cirno-207": "Ice Sign \"Sword Freezer\"",
    "cirno-205": "Ice Sign \"Fairy Spin\"",
    "cirno-208": "Ice Clump \"Great Crusher\"",
    "cirno-206": "Blowing Ice \"Ice Tornado\"",
    "cirno-203": "Cold Body \"Super Ice Kick\"",
    "cirno-202": "Ice Clump \"Cold Sprinkler\"",
    "cirno-111": "Icicle Sword",
    "cirno-109": "Ice Kick",
    "cirno-110": "Frozen Technique",
    "cirno-104": "Frost Pillars",
    "cirno-108": "Freezing Lasers",
    "cirno-107": "Icicle Rise",
    "cirno-101": "Midsummer Snowman",
    "cirno-103": "Freeze Touch Me",
    "cirno-106": "Icicle Bomb",
    "cirno-102": "Little Iceberg",
    "cirno-105": "Ice Charge",
    "cirno-100": "Icicle Shoot",
    "meiling-111": "Colorful Rain",
    "meiling-109": "Tiger Chi Release",
    "meiling-110": "Sky Dragon Kick",
    "meiling-108": "Kick of Showering Brilliance",
    "meiling-104": "Intense Rainbow Fist",
    "meiling-102": "Yellow Quake Kick",
    "meiling-106": "Earth Dragon Wave",
    "meiling-107": "Water Taichi Fist",
    "meiling-105": "Crimson Energy Release",
    "meiling-101": "Crimson Cannon",
    "meiling-103": "Fragrant Wave",
    "meiling-100": "Spiral-Light Steps",
    "meiling-201": "Colorful Sign \"Colorful Light Chaotic Dance\"",
    "meiling-200": "Colorful Sign \"Colorful Light Wind Chime\"",
    "meiling-211": "Chi Sign \"Fierce Tiger Energy Release\"",
    "meiling-208": "Colorful Flower \"Rainbow Taijiquan\"",
    "meiling-209": "Flowery Sign \"Colorful Light Lotus Flower Palm\"",
    "meiling-204": "Attack Sign \"Roc Fist\"",
    "meiling-206": "Rainbow Sign \"Intense Rainbow Fist\"",
    "meiling-207": "Chi Sign \"Earth Dragon Sky Dragon Kick\"",
    "meiling-205": "Fiery Attack \"Roc-Killing Fist\"",
    "meiling-203": "Star Chi \"Earth-Moving Star Bullets\"",
    "meiling-202": "Chi Sign \"Star Bullets\"",
    "utsuho-12": "Atomic Fire \"Artificial Sun's Spot\"",
    "utsuho-4": "Atomic Fire \"Uncontainable Nuclear Reaction Dive\"",
    "utsuho-8": "\"Hot Jupiter Descent Model\"",
    "utsuho-0": "Heat Sign \"Break Prominence\"",
    "utsuho-109": "Radiant Blade",
    "utsuho-108": "Melting Pummel Kick",
    "utsuho-107": "Retro Atomic Model",
    "utsuho-106": "Shooting Star",
    "utsuho-104": "Rocket Dive",
    "utsuho-105": "Hell Geyser",
    "utsuho-100": "Flare Up",
    "utsuho-103": "Shooting Star",
    "utsuho-101": "Ground Melt",
    "utsuho-102": "Break Sun",
    "utsuho-111": "Vengeful Nuclear Spirits",
    "utsuho-110": "Hell Wave Cannon",
    "utsuho-214": "\"Abyss Nova\"",
    "utsuho-213": "Light Cover \"Nuclear Heat Visor\"",
    "utsuho-210": "Atomic Fire \"Uncontainable Nuclear Reaction Dive\"",
    "utsuho-211": "Control \"Self Tokamak\"",
    "utsuho-212": "\"Subterranean Sun\"",
    "utsuho-209": "Crow Sign \"Yatagarasu Dive\"",
    "utsuho-208": "Light Energy \"High-Tension Blade\"",
    "utsuho-207": "Geothermal \"Nuclear Blaze Geyser\"",
    "utsuho-206": "\"Hell's Artificial Sun\"",
    "utsuho-205": "Nuclear Sign \"Creeping Sun\"",
    "utsuho-203": "Blazing Star \"Fixed Star\"",
    "utsuho-201": "Explosion Sign \"Giga Flare\"",
    "utsuho-200": "Explosion Sign \"Mega Flare\"",
    "utsuho-204": "Blazing Star \"Ten Evil Stars\"",
    "suwako-16": "\"Divine Battle Above Gensokyo\"",
    "suwako-12": "\"Magma Amphibian\"",
    "suwako-8": "\"Hellish Heat Geyser\"",
    "suwako-4": "Divine Tool \"Moriya's Iron Ring\"",
    "suwako-0": "Clap \"Daidarabotchi's Worship\"",
    "suwako-110": "Stone Frog God",
    "suwako-109": "Mr. Long-Arm and Mr. Long-Leg",
    "suwako-108": "Rain-calling Frog",
    "suwako-104": "Water Frog God",
    "suwako-102": "Lake of Great Earth",
    "suwako-100": "Ancient Geyser",
    "suwako-107": "Scourged Earth",
    "suwako-106": "Ancient Jade",
    "suwako-103": "Native God's Scourge",
    "suwako-105": "Ancient Iron Ring",
    "suwako-101": "Giant Toad God",
    "suwako-111": "Mishaguji Scourge",
    "suwako-202": "Party Start \"Two Bows, Two Claps, and One Bow\"",
    "suwako-200": "Native God \"Moriya God\"",
    "suwako-201": "Spring Sign \"Suwa Clear Water\"",
    "suwako-212": "Frog Nap \"Can Always Hibernate\"",
    "suwako-209": "Native God \"Red Frogs of Houei 4\"",
    "suwako-208": "Scourge God \"Mishaguchi-sama\"",
    "suwako-207": "Native God \"Lord Long-Arm and Lord Long-Leg\"",
    "suwako-206": "Frog Hunt \"The Snake Eats the Croaking Frog\"",
    "suwako-205": "Spring Sign \"Jade of the Horrid River\"",
    "suwako-204": "Divine Tool \"Moriya's Iron Ring\"",
    "suwako-203": "Native God \"Froggy Braves the Wind and Rain\"",
    "namazu-16": "Great Catfish \"With This Ends the Fleeting World!\"",
    "namazu-12": "Catfish \"All-Electrical for Ecology!\"",
    "namazu-8": "Catfish \"I'm Charging Up!\"",
    "namazu-4": "Catfish \"The Earth Liquefies into Mud!\"",
    "namazu-0": "Catfish \"See? The World is Shaking!\""
}