{
    "0": "蝶符「ミニットスケールス」",
    "2": "蝶符「アゲハの鱗粉」",
    "4": "蝶符「フラッタリングサマー」",
    "6": "蝶符「真夏の羽ばたき」",
    "8": "雨符「囚われの秋雨」",
    "10": "雨符「呪われた柴榑雨」",
    "12": "刃符「山姥の包丁研ぎ」",
    "14": "刃符「山姥の鬼包丁研ぎ」",
    "16": "尽符「マウンテンマーダー」",
    "18": "尽符「ブラッディマウンテンマーダー」",
    "20": "春符「サプライズスプリング」",
    "22": "犬符「野良犬の散歩」",
    "24": "狗符「山狗の散歩」",
    "26": "独楽「コマ犬回し」",
    "29": "独楽「カールアップアンドダイ」",
    "30": "狛符「独り阿吽の呼吸」",
    "story-reimu-stage1-2-3": "Star Sign \"Occultation\"",
    "story-reimu-stage1-2-2": "Star Sign \"Occultation\"",
    "story-reimu-stage1-2-1": "Star Sign \"Occultation\"",
    "story-reimu-stage1-3-4": "*Cursed Portraits of Past Principals*",
    "story-reimu-stage1-3-3": "*Cursed Portraits of Past Principals*",
    "story-reimu-stage1-3-2": "*Cursed Portraits of Past Principals*",
    "story-reimu-stage1-3-1": "*Cursed Portraits of Past Principals*",
    "story-reimu-stage2-3-3": "*Hand that Grants Wishes Until Death*",
    "story-reimu-stage2-3-2": "*Hand that Grants Wishes Until Death*",
    "story-reimu-stage2-3-1": "*Hand that Grants Wishes Until Death*",
    "story-reimu-stage2-2-3": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-reimu-stage2-2-1": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-reimu-stage2-2-2": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-marisa-stage1-2-3": "Barrier \"The Home Where One Lays One's Head\"",
    "story-marisa-stage1-2-2": "Barrier \"The Home Where One Lays One's Head\"",
    "story-marisa-stage1-2-1": "Barrier \"The Home Where One Lays One's Head\"",
    "story-marisa-stage3-1-3": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-marisa-stage3-1-2": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-marisa-stage3-1-1": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
	"story-marisa-stage3-2-3": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-marisa-stage3-2-2": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-marisa-stage3-2-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-marisa-stage2-2-3": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-marisa-stage2-2-2": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-marisa-stage2-2-1": "Evil Sign \"Eight-Shaku Occult Pillar\"",
	"story-marisa-stage4-2-4": "Unidentified \"Scrolls of Flying Objects\"",
    "story-marisa-stage4-2-3": "Unidentified \"Scrolls of Flying Objects\"",
    "story-marisa-stage4-2-2": "Unidentified \"Scrolls of Flying Objects\"",
    "story-marisa-stage4-2-1": "Unidentified \"Scrolls of Flying Objects\"",
	"story-marisa-stage4-3-4": "*Crowded Alien Ball*",
    "story-marisa-stage4-3-3": "*Crowded Alien Ball*",
    "story-marisa-stage4-3-2": "*Crowded Alien Ball*",
    "story-marisa-stage4-3-1": "*Crowded Alien Ball*",
    "story-marisa-stage4-4-4": "*Let's Go Home Soon, Aliens!*",
    "story-marisa-stage4-4-3": "*Let's Go Home Soon, Aliens!*",
    "story-marisa-stage4-4-2": "*Let's Go Home Soon, Aliens!*",
    "story-marisa-stage4-4-1": "*Let's Go Home Soon, Aliens!*",
	"story-marisa-stage5-2-1": "Fiend \"Hermetic Cape\"",
    "story-marisa-stage5-3-1": "*The Great Fiend's Arteries and Veins*",
    "story-marisa-stage5-3-3": "*The Great Fiend's Arteries and Veins*",
    "story-marisa-stage6-2-4": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-marisa-stage6-2-3": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-marisa-stage6-2-2": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-marisa-stage6-2-1": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-marisa-stage6-3-3": "*Hand that Grants Wishes Until Death*",
    "story-marisa-stage6-3-2": "*Hand that Grants Wishes Until Death*",
    "story-marisa-stage6-3-1": "*Hand that Grants Wishes Until Death*",
    "story-marisa-stage6-4-3": "*The Monkey's Paw Dreams of the Occult*",
    "story-marisa-stage6-4-2": "*The Monkey's Paw Dreams of the Occult*",
    "story-marisa-stage6-4-1": "*The Monkey's Paw Dreams of the Occult*",
    "story-marisa-stage7-2-2": "Psychokinesis \"Psychexplosion\"",
    "story-marisa-stage7-2-1": "Psychokinesis \"Psychexplosion\"",
    "story-marisa-stage7-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-marisa-stage7-2-3": "Psychokinesis \"Psychexplosion\"",
    "story-marisa-stage7-3-3": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-marisa-stage7-3-2": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-marisa-stage7-4-3": "*Occultician of the Present World*",
    "story-marisa-stage7-4-2": "*Occultician of the Present World*",
    "story-marisa-stage7-4-1": "*Occultician of the Present World*",
    "story-kasen-stage1-2-3": "Barrier \"The Home Where One Lays One's Head\"",
    "story-kasen-stage1-2-2": "Barrier \"The Home Where One Lays One's Head\"",
    "story-kasen-stage1-2-1": "Barrier \"The Home Where One Lays One's Head\"",
    "story-kasen-stage2-2-3": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-kasen-stage2-2-2": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-kasen-stage2-2-1": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-kasen-stage3-1-3": "*Split-Mouthed Emotion*",
    "story-kasen-stage3-1-2": "*Split-Mouthed Emotion*",
    "story-kasen-stage3-1-1": "*Split-Mouthed Emotion*",
    "story-kasen-stage4-2-3": "Unidentified \"Scrolls of Flying Objects\"",
    "story-kasen-stage4-2-2": "Unidentified \"Scrolls of Flying Objects\"",
    "player-usami(13)-2": "Psychokinesis \"Psychokinesis App\"",
    "player-usami(13)-3": "Psychokinesis \"Telekinesis: Radio Tower\"",
    "story-kasen-stage4-3-3": "*Crowded Alien Ball*",
    "story-kasen-stage4-3-2": "*Crowded Alien Ball*",
    "player-usami(13)-4": "Psychokinesis \"Telekinesis: Radio Tower\"",
    "story-kasen-stage4-3-1": "*Crowded Alien Ball*",
    "story-kasen-stage4-2-1": "Unidentified \"Scrolls of Flying Objects\"",
    "story-kasen-stage5-3-3": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-kasen-stage5-2-2": "Psychokinesis \"Psychexplosion\"",
    "story-kasen-stage5-2-1": "Psychokinesis \"Psychexplosion\"",
    "story-kasen-stage5-3-2": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-kasen-stage5-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-kasen-stage5-2-3": "Psychokinesis \"Psychexplosion\"",
    "story-kasen-stage5-4-1": "*Occultician of the Present World*",
    "story-kasen-stage5-4-2": "*Occultician of the Present World*",
    "story-kasen-stage5-4-3": "*Occultician of the Present World*",
    "player-kokoro(9)-2": "Possession \"Four Humors Possession\"",
    "player-kokoro(9)-3": "Melancholy Mask\n\"The Man of Qi Worries about the Earth\"",
    "player-kokoro(9)-4": "Melancholy Mask \"The Man of Qi Worries about the Earth\"",
    "story-ichirin-stage1-2-3": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-ichirin-stage1-2-2": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-ichirin-stage1-2-1": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-ichirin-stage2-2-3": "Star Sign \"Occultation\"",
    "story-ichirin-stage2-2-2": "Star Sign \"Occultation\"",
    "story-ichirin-stage2-2-1": "Star Sign \"Occultation\"",
    "player-koishi(7)-4": "Dream Sign \"Ancestors are Watching You\"",
    "story-ichirin-stage3-2-3": "Big Catch \"Midair Giant Rotation Fishing Method\"",
    "story-ichirin-stage3-2-2": "Big Catch \"Midair Giant Rotation Fishing Method\"",
    "story-ichirin-stage3-2-1": "Big Catch \"Midair Giant Rotation Fishing Method\"",
    "story-ichirin-stage3-3-3": "*Country of Illusion, Blefuscu*",
    "story-ichirin-stage3-3-2": "*Country of Illusion, Blefuscu*",
    "story-ichirin-stage3-3-1": "*Country of Illusion, Blefuscu*",
    "story-ichirin-stage4-2-2": "Fiend \"Hermetic Cape\"",
    "story-ichirin-stage4-2-3": "Fiend \"Hermetic Cape\"",
    "story-ichirin-stage4-2-1": "Fiend \"Hermetic Cape\"",
    "story-ichirin-stage4-4-3": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-ichirin-stage4-4-2": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-ichirin-stage4-4-1": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-ichirin-stage4-3-3": "*The Great Fiend's Arteries and Veins*",
    "story-ichirin-stage4-3-2": "*The Great Fiend's Arteries and Veins*",
    "story-ichirin-stage4-3-1": "*The Great Fiend's Arteries and Veins*",
    "player-koishi(7)-3": "Dream Sign \"Ancestors are Watching You\"",
    "player-koishi(7)-2": "Instinct \"Release of the Id\"",
    "story-hijiri-stage2-2-3": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-hijiri-stage2-2-2": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-hijiri-stage2-2-1": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-hijiri-stage1-2-3": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-hijiri-stage1-2-2": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-hijiri-stage1-2-1": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "player-nitori(6)-2": "Bubble Sign \"Fire! Bubble Dragon\"",
    "player-nitori(6)-3": "Battle Machine \"Fly! Sanpei Fight\"",
    "player-nitori(6)-4": "Battle Machine \"Fly! Sanpei Fight\"",
    "player-sinmyoumaru(12)-2": "Inchling\n\"One-Inch Samurai with a Half-Inch Soul\"",
    "player-sinmyoumaru(12)-3": "Fishing Sign\n\"Adorable Tai Gong Wang\"",
    "player-sinmyoumaru(12)-4": "Fishing Sign \"Adorable Tai Gong Wang\"",
    "story-hijiri-stage3-1-3": "*Perfect Nessie Cultivation Method*",
    "story-hijiri-stage3-1-2": "*Perfect Nessie Cultivation Method*",
    "story-hijiri-stage3-1-1": "*Perfect Nessie Cultivation Method*",
    "story-hijiri-stage4-3-3": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-hijiri-stage4-3-2": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-hijiri-stage4-3-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-hijiri-stage4-2-3": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-hijiri-stage4-2-2": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-hijiri-stage4-2-1": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "player-mokou(11)-2": "Undying\n\"'South Wind, Clear Sky' Soaring Kick\"",
    "story-hijiri-stage5-2-1": "Fiend \"Hermetic Cape\"",
    "story-hijiri-stage5-3-1": "*The Great Fiend's Arteries and Veins*",
    "story-hijiri-stage5-3-3": "*The Great Fiend's Arteries and Veins*",
    "player-mokou(11)-3": "Cursed Talisman\n\"Indiscriminate Ignition Cards\"",
    "story-hijiri-stage5-4-1": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-hijiri-stage5-4-2": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-hijiri-stage5-4-3": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-hijiri-stage5-2-3": "Fiend \"Hermetic Cape\"",
    "story-hijiri-stage5-2-2": "Fiend \"Hermetic Cape\"",
    "story-hijiri-stage5-3-2": "*The Great Fiend's Arteries and Veins*",
    "player-mokou(11)-4": "Cursed Talisman \"Indiscriminate Ignition Cards\"",
    "player-reimu(0)-2": "Divine Arts\n\"Omnidirectional Dragon-Slaying Circle\"",
    "story-futo-stage3-3-2": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-futo-stage3-3-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "player-reimu(0)-3": "Treasure \"Ying-Yang Asuka'i\"",
    "story-futo-stage1-2-1": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-futo-stage1-2-3": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-futo-stage1-2-2": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "player-reimu(0)-4": "Treasure \"Ying-Yang Asuka'i\"",
    "story-futo-stage2-2-3": "Barrier \"The Home Where One Lays One's Head\"",
    "story-futo-stage2-2-2": "Barrier \"The Home Where One Lays One's Head\"",
    "story-futo-stage2-2-1": "Barrier \"The Home Where One Lays One's Head\"",
    "story-futo-stage3-2-3": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-futo-stage3-2-2": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-futo-stage3-2-1": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-futo-stage3-3-3": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "player-marisa(1)-2": "Comet \"Blazing Star\"",
    "player-marisa(1)-3": "Star Sign \"Satellite Illusion\"",
    "story-futo-stage4-2-3": "Supersonic Speed \"Old Lady's Sprint\"",
    "story-futo-stage4-2-2": "Supersonic Speed \"Old Lady's Sprint\"",
    "player-marisa(1)-4": "Star Sign \"Satellite Illusion\"",
    "story-futo-stage4-3-3": "*Highway Turbo Air Turn*",
    "story-futo-stage4-3-2": "*Highway Turbo Air Turn*",
    "story-futo-stage4-3-1": "*Highway Turbo Air Turn*",
    "story-futo-stage4-2-1": "Supersonic Speed \"Old Lady's Sprint\"",
    "player-kasen(10)-2": "Dragon Sign \"Dragon's Growl\"",
    "story-futo-stage4-4-3": "*Turbo Granny Rides for Her Life*",
    "story-futo-stage4-4-2": "*Turbo Granny Rides for Her Life*",
    "story-futo-stage4-4-1": "*Turbo Granny Rides for Her Life*",
    "player-kasen(10)-3": "Hawk Sign \"Hawk Beacon\"",
    "player-kasen(10)-4": "Hawk Sign \"Hawk Beacon\"",
    "player-ichirin(2)-2": "Cumulonimbus\n\"Foreseeing Nyuudou Cloud\"",
    "player-ichirin(2)-3": "Clenched Fist\n\"Deadly Wind of Penitence\"",
    "player-ichirin(2)-4": "Clenched Fist \"Deadly Wind of Penitence\"",
    "story-miko-stage1-2-1": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-miko-stage1-2-3": "Plate Sign \"Okiku Driven to Desperation\"",
    "player-hijiri(3)-2": "Heaven Sign\n\"Brilliance of Mahavairocana\"",
    "story-miko-stage2-2-2": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-miko-stage1-2-2": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-miko-stage2-2-3": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-miko-stage2-2-1": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-miko-stage3-1-1": "*Perfect Nessie Cultivation Method*",
    "player-hijiri(3)-3": "Heaven Sign\n\"Five-Element Mountain of Shakyamuni\"",
    "story-miko-stage3-1-2": "*Perfect Nessie Cultivation Method*",
    "story-miko-stage3-1-3": "*Perfect Nessie Cultivation Method*",
    "story-miko-stage4-2-1": "Big Catch \"Midair Giant Rotation Fishing Method\"",
    "story-miko-stage4-2-3": "Big Catch \"Midair Giant Rotation Fishing Method\"",
    "story-miko-stage4-2-2": "Big Catch \"Midair Giant Rotation Fishing Method\"",
    "player-hijiri(3)-4": "Heaven Sign \"Five-Element Mountain of Shakyamuni\"",
    "story-miko-stage4-3-3": "*Country of Illusion, Blefuscu*",
    "story-miko-stage4-3-2": "*Country of Illusion, Blefuscu*",
    "story-miko-stage4-3-1": "*Country of Illusion, Blefuscu*",
    "story-miko-stage5-2-3": "Supersonic Speed \"Old Lady's Sprint\"",
    "story-miko-stage5-2-2": "Supersonic Speed \"Old Lady's Sprint\"",
    "story-miko-stage5-2-1": "Supersonic Speed \"Old Lady's Sprint\"",
    "player-futo(4)-2": "Blaze Sign \"Taiyi True Fire\"",
    "player-futo(4)-3": "Fate \"Gate Opening for Catastrophe\"",
    "player-futo(4)-4": "Fate \"Gate Opening for Catastrophe\"",
    "story-miko-stage5-3-1": "*Highway Turbo Air Turn*",
    "story-miko-stage5-3-3": "*Highway Turbo Air Turn*",
    "story-miko-stage5-3-2": "*Highway Turbo Air Turn*",
    "story-miko-stage5-4-1": "*Turbo Granny Rides for Her Life*",
    "story-miko-stage5-4-2": "*Turbo Granny Rides for Her Life*",
    "story-miko-stage5-4-3": "*Turbo Granny Rides for Her Life*",
    "player-miko(5)-2": "Tao Sign\n\"Heavenly Way Atop One's Palm\"",
    "player-miko(5)-3": "Human Sign\n\"Tradition of Just Rewards\"",
    "player-miko(5)-4": "Human Sign \"Tradition of Just Rewards\"",
    "player-mamizou(8)-2": "Transformation\n\"Youkai World Gate of One Hundred Demons\"",
    "player-mamizou(8)-3": "Transformation\n\"Futatsuiwa Clan's Curse\"",
    "player-mamizou(8)-4": "Transformation \"Futatsuiwa Clan's Curse\"",
    "story-mamizou-stage1-2-3": "Star Sign \"Occultation\"",
    "story-mamizou-stage1-2-2": "Star Sign \"Occultation\"",
    "story-mamizou-stage1-2-1": "Star Sign \"Occultation\"",
    "story-mamizou-stage5-2-1": "Psychokinesis \"Psychexplosion\"",
    "story-mamizou-stage5-2-3": "Psychokinesis \"Psychexplosion\"",
    "story-mamizou-stage5-2-2": "Psychokinesis \"Psychexplosion\"",
    "story-mamizou-stage5-3-3": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-mamizou-stage5-3-2": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-mamizou-stage5-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-mamizou-stage5-4-3": "*Occultician of the Present World*",
    "story-mamizou-stage5-4-1": "*Occultician of the Present World*",
    "story-mamizou-stage2-2-3": "Barrier \"The Home Where One Lays One's Head\"",
    "story-mamizou-stage2-2-2": "Barrier \"The Home Where One Lays One's Head\"",
    "story-mamizou-stage2-2-1": "Barrier \"The Home Where One Lays One's Head\"",
    "story-mamizou-stage3-1-3": "*Split-Mouthed Emotion*",
    "story-mamizou-stage3-1-2": "*Split-Mouthed Emotion*",
    "story-mamizou-stage3-1-1": "*Split-Mouthed Emotion*",
    "story-mamizou-stage4-4-3": "*The Monkey's Paw Dreams of the Occult*",
    "story-mamizou-stage4-4-2": "*The Monkey's Paw Dreams of the Occult*",
    "story-mamizou-stage4-4-1": "*The Monkey's Paw Dreams of the Occult*",
    "story-mamizou-stage4-3-3": "*Hand that Grants Wishes Until Death*",
    "story-mamizou-stage4-3-2": "*Hand that Grants Wishes Until Death*",
    "story-mamizou-stage4-3-1": "*Hand that Grants Wishes Until Death*",
    "story-mamizou-stage5-4-2": "*Occultician of the Present World*",
    "story-mamizou-stage4-2-3": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-mamizou-stage4-2-2": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-mamizou-stage4-2-1": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-usami-stage1-2-1": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-usami-stage1-2-2": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-usami-stage1-2-3": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-usami-stage1-3-1": "*Hand that Grants Wishes Until Death*",
    "story-usami-stage1-3-2": "*Hand that Grants Wishes Until Death*",
    "story-usami-stage1-3-3": "*Hand that Grants Wishes Until Death*",
    "story-usami-stage1-4-1": "*The Monkey's Paw Dreams of the Occult*",
    "story-usami-stage1-4-2": "*The Monkey's Paw Dreams of the Occult*",
    "story-usami-stage1-4-3": "*The Monkey's Paw Dreams of the Occult*",
    "story-usami-stage2-2-1": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-usami-stage2-2-2": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-usami-stage2-2-3": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-mokou-stage1-2-3": "Barrier \"The Home Where One Lays One's Head\"",
    "story-mokou-stage1-2-2": "Barrier \"The Home Where One Lays One's Head\"",
    "story-mokou-stage1-2-1": "Barrier \"The Home Where One Lays One's Head\"",
    "story-usami-stage2-3-1": "*A Midsummer Night Trapped by a Mysterious Woman*",
    "story-usami-stage2-3-2": "*A Midsummer Night Trapped by a Mysterious Woman*",
    "story-usami-stage2-3-3": "*A Midsummer Night Trapped by a Mysterious Woman*",
    "story-usami-stage3-1-2": "*Split-Mouthed Emotion*",
    "story-usami-stage3-1-1": "*Split-Mouthed Emotion*",
    "story-usami-stage3-1-3": "*Split-Mouthed Emotion*",
    "story-mokou-stage3-1-3": "*Perfect Nessie Cultivation Method*",
    "story-mokou-stage3-1-2": "*Perfect Nessie Cultivation Method*",
    "story-mokou-stage3-1-1": "*Perfect Nessie Cultivation Method*",
    "story-mokou-stage2-2-3": "Star Sign \"Occultation\"",
    "story-mokou-stage2-2-2": "Star Sign \"Occultation\"",
    "story-mokou-stage2-2-1": "Star Sign \"Occultation\"",
    "story-usami-stage4-2-1": "Star Sign \"Occultation\"",
    "story-usami-stage4-2-2": "Star Sign \"Occultation\"",
    "story-usami-stage4-2-3": "Star Sign \"Occultation\"",
    "story-usami-stage4-3-1": "*Cursed Portraits of Past Principals*",
    "story-mokou-stage4-2-3": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-mokou-stage4-2-2": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-mokou-stage4-2-1": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-usami-stage4-3-2": "*Cursed Portraits of Past Principals*",
    "story-usami-stage4-3-3": "*Cursed Portraits of Past Principals*",
    "story-usami-stage5-2-1": "Big Catch \"Midair Giant Rotation Fishing Method\"",
    "story-usami-stage4-4-1": "*Nighttime School Horror Story Pilgrimage*",
    "story-usami-stage4-4-2": "*Nighttime School Horror Story Pilgrimage*",
    "story-mokou-stage5-4-1": "*Occultician of the Present World*",
    "story-mokou-stage5-4-2": "*Occultician of the Present World*",
    "story-mokou-stage5-4-3": "*Occultician of the Present World*",
    "story-usami-stage4-4-3": "*Nighttime School Horror Story Pilgrimage*",
    "story-mokou-stage4-3-1": "*Hand that Grants Wishes Until Death*",
    "story-mokou-stage4-3-3": "*Hand that Grants Wishes Until Death*",
    "story-usami-stage5-2-2": "Big Catch \"Midair Giant Rotation Fishing Method\"",
    "story-mokou-stage4-3-2": "*Hand that Grants Wishes Until Death*",
    "story-usami-stage5-2-3": "Big Catch \"Midair Giant Rotation Fishing Method\"",
    "story-mokou-stage5-3-3": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-mokou-stage5-2-3": "Psychokinesis \"Psychexplosion\"",
    "story-mokou-stage5-2-2": "Psychokinesis \"Psychexplosion\"",
    "story-usami-stage5-3-1": "*Country of Illusion, Blefuscu*",
    "story-mokou-stage5-3-2": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-mokou-stage5-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-usami-stage5-3-2": "*Country of Illusion, Blefuscu*",
    "story-mokou-stage5-2-1": "Psychokinesis \"Psychexplosion\"",
    "story-mokou-stage4-4-3": "*The Monkey's Paw Dreams of the Occult*",
    "story-mokou-stage4-4-1": "*The Monkey's Paw Dreams of the Occult*",
    "story-usami-stage5-3-3": "*Country of Illusion, Blefuscu*",
    "story-mokou-stage4-4-2": "*The Monkey's Paw Dreams of the Occult*",
    "story-usami-stage6-2-1": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-usami-stage6-2-2": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-usami-stage6-2-3": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-sinmyoumaru-stage1-2-3": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-sinmyoumaru-stage1-2-2": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-sinmyoumaru-stage1-2-1": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-usami-stage6-3-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-usami-stage6-3-2": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-usami-stage6-3-3": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-usami-stage7-2-1": "Fiend \"Hermetic Cape\"",
    "story-usami-stage7-2-2": "Fiend \"Hermetic Cape\"",
    "story-sinmyoumaru-stage5-4-3": "*Occultician of the Present World*",
    "story-sinmyoumaru-stage5-3-3": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-usami-stage7-2-3": "Fiend \"Hermetic Cape\"",
    "story-sinmyoumaru-stage5-4-1": "*Occultician of the Present World*",
    "story-sinmyoumaru-stage5-3-2": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-usami-stage7-3-1": "*The Great Fiend's Arteries and Veins*",
    "story-usami-stage7-3-2": "*The Great Fiend's Arteries and Veins*",
    "story-sinmyoumaru-stage5-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-sinmyoumaru-stage5-4-2": "*Occultician of the Present World*",
    "story-usami-stage7-3-3": "*The Great Fiend's Arteries and Veins*",
    "story-usami-stage7-4-1": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-usami-stage7-4-2": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-usami-stage7-4-3": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-sinmyoumaru-stage4-4-3": "*Let's Go Home Soon, Aliens!*",
    "story-sinmyoumaru-stage4-4-2": "*Let's Go Home Soon, Aliens!*",
    "story-sinmyoumaru-stage4-4-1": "*Let's Go Home Soon, Aliens!*",
    "story-sinmyoumaru-stage5-2-1": "Psychokinesis \"Psychexplosion\"",
    "story-sinmyoumaru-stage5-2-3": "Psychokinesis \"Psychexplosion\"",
    "story-sinmyoumaru-stage5-2-2": "Psychokinesis \"Psychexplosion\"",
    "story-sinmyoumaru-stage4-3-3": "*Crowded Alien Ball*",
    "story-sinmyoumaru-stage4-3-2": "*Crowded Alien Ball*",
    "story-sinmyoumaru-stage4-3-1": "*Crowded Alien Ball*",
    "story-sinmyoumaru-stage4-2-3": "Unidentified \"Scrolls of Flying Objects\"",
    "story-sinmyoumaru-stage4-2-2": "Unidentified \"Scrolls of Flying Objects\"",
    "story-sinmyoumaru-stage4-2-1": "Unidentified \"Scrolls of Flying Objects\"",
    "story-sinmyoumaru-stage3-1-3": "*Cursed Dial-and-Drop Phone*",
    "story-sinmyoumaru-stage3-1-2": "*Cursed Dial-and-Drop Phone*",
    "story-sinmyoumaru-stage3-1-1": "*Cursed Dial-and-Drop Phone*",
    "story-sinmyoumaru-stage2-2-3": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-sinmyoumaru-stage2-2-2": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-sinmyoumaru-stage2-2-1": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-reimuB-stage1-2-1": "Unidentified \"Scrolls of Flying Objects\"",
    "story-reimuB-stage1-2-2": "Unidentified \"Scrolls of Flying Objects\"",
    "story-reimuB-stage1-2-3": "Unidentified \"Scrolls of Flying Objects\"",
    "story-reimuB-stage1-3-1": "*Crowded Alien Ball*",
    "story-reimuB-stage1-3-2": "*Crowded Alien Ball*",
    "story-reimuB-stage1-3-3": "*Crowded Alien Ball*",
    "story-reimuB-stage1-4-1": "*Let's Go Home Soon, Aliens!*",
    "story-reimuB-stage1-4-2": "*Let's Go Home Soon, Aliens!*",
    "story-reimuB-stage1-4-3": "*Let's Go Home Soon, Aliens!*",
    "story-nitori-stage4-4-2": "*Let's Go Home Soon, Aliens!*",
    "story-nitori-stage4-4-3": "*Let's Go Home Soon, Aliens!*",
    "story-nitori-stage4-3-3": "*Crowded Alien Ball*",
    "story-nitori-stage4-4-1": "*Let's Go Home Soon, Aliens!*",
    "story-nitori-stage4-3-2": "*Crowded Alien Ball*",
    "story-reimuB-stage2-2-1": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-reimuB-stage2-2-2": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-nitori-stage4-2-3": "Unidentified \"Scrolls of Flying Objects\"",
    "story-reimuB-stage2-2-3": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-nitori-stage4-3-1": "*Crowded Alien Ball*",
    "story-nitori-stage4-2-1": "Unidentified \"Scrolls of Flying Objects\"",
    "story-nitori-stage3-3-3": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-nitori-stage3-3-2": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-nitori-stage3-3-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-reimuB-stage2-3-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-reimuB-stage2-3-2": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-nitori-stage4-2-2": "Unidentified \"Scrolls of Flying Objects\"",
    "story-reimuB-stage2-3-3": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-nitori-stage1-2-1": "Star Sign \"Occultation\"",
    "story-nitori-stage2-2-1": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-nitori-stage1-2-3": "Star Sign \"Occultation\"",
    "story-nitori-stage1-2-2": "Star Sign \"Occultation\"",
    "story-nitori-stage2-2-3": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-nitori-stage2-2-2": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-nitori-stage3-2-3": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-nitori-stage3-2-2": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-nitori-stage3-2-1": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-reimuB-stage3-2-1": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-reimuB-stage3-2-2": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-reimuB-stage3-2-3": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-reimuB-stage3-3-1": "*Hand that Grants Wishes Until Death*",
    "story-reimuB-stage3-3-2": "*Hand that Grants Wishes Until Death*",
    "story-reimuB-stage3-3-3": "*Hand that Grants Wishes Until Death*",
    "story-reimuB-stage3-4-1": "*The Monkey's Paw Dreams of the Occult*",
    "story-reimuB-stage3-4-2": "*The Monkey's Paw Dreams of the Occult*",
    "story-reimuB-stage3-4-3": "*The Monkey's Paw Dreams of the Occult*",
    "story-reimuB-stage4-2-1": "Psychokinesis \"Psychexplosion\"",
    "story-reimuB-stage4-2-2": "Psychokinesis \"Psychexplosion\"",
    "story-reimuB-stage4-2-3": "Psychokinesis \"Psychexplosion\"",
    "story-koishi-stage1-2-3": "Barrier \"The Home Where One Lays One's Head\"",
    "story-koishi-stage1-2-2": "Barrier \"The Home Where One Lays One's Head\"",
    "story-koishi-stage1-2-1": "Barrier \"The Home Where One Lays One's Head\"",
    "story-reimuB-stage4-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-reimuB-stage4-3-2": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-reimuB-stage4-3-3": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-reimuB-stage4-4-1": "*Occultician of the Present World*",
    "story-reimuB-stage4-4-2": "*Occultician of the Present World*",
    "story-koishi-stage4-3-3": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-koishi-stage4-4-1": "*Occultician of the Present World*",
    "story-koishi-stage4-4-2": "*Occultician of the Present World*",
    "story-koishi-stage4-4-3": "*Occultician of the Present World*",
    "story-reimuB-stage4-4-3": "*Occultician of the Present World*",
    "story-koishi-stage4-3-2": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-koishi-stage4-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-reimuB-stage4-5-1": "*Esoteric Seven of Profound Secrets*",
    "story-koishi-stage4-2-2": "Psychokinesis \"Psychexplosion\"",
    "story-koishi-stage4-2-1": "Psychokinesis \"Psychexplosion\"",
    "story-koishi-stage3-4-2": "*The Monkey's Paw Dreams of the Occult*",
    "story-reimuB-stage4-5-2": "*Esoteric Seven of Profound Secrets*",
    "story-koishi-stage4-2-3": "Psychokinesis \"Psychexplosion\"",
    "story-reimuB-stage4-5-3": "*Esoteric Seven of Profound Secrets*",
    "story-koishi-stage3-3-1": "*Hand that Grants Wishes Until Death*",
    "story-koishi-stage3-4-1": "*The Monkey's Paw Dreams of the Occult*",
    "story-koishi-stage3-4-3": "*The Monkey's Paw Dreams of the Occult*",
    "story-koishi-stage3-3-3": "*Hand that Grants Wishes Until Death*",
    "story-koishi-stage3-3-2": "*Hand that Grants Wishes Until Death*",
    "story-koishi-stage2-2-3": "Star Sign \"Occultation\"",
    "story-koishi-stage2-2-2": "Star Sign \"Occultation\"",
    "story-koishi-stage2-2-1": "Star Sign \"Occultation\"",
    "story-koishi-stage3-2-3": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-koishi-stage3-2-2": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-koishi-stage3-2-1": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-kokoro-stage1-2-1": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-kokoro-stage1-2-2": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-kokoro-stage4-3-1": "*The Great Fiend's Arteries and Veins*",
    "story-kokoro-stage4-4-1": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-kokoro-stage1-2-3": "Evil Sign \"Eight-Shaku Occult Pillar\"",
    "story-kokoro-stage4-4-3": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-kokoro-stage4-4-2": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-kokoro-stage4-3-3": "*The Great Fiend's Arteries and Veins*",
    "story-kokoro-stage4-3-2": "*The Great Fiend's Arteries and Veins*",
    "story-kokoro-stage2-1-1": "*Perfect Nessie Cultivation Method*",
    "story-kokoro-stage2-1-2": "*Perfect Nessie Cultivation Method*",
    "story-kokoro-stage2-1-3": "*Perfect Nessie Cultivation Method*",
    "story-kokoro-stage3-2-1": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-kokoro-stage3-2-2": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-kokoro-stage3-2-3": "Plate Sign \"Okiku Driven to Desperation\"",
    "story-kokoro-stage4-2-3": "Fiend \"Hermetic Cape\"",
    "story-kokoro-stage4-2-2": "Fiend \"Hermetic Cape\"",
    "story-kokoro-stage4-2-1": "Fiend \"Hermetic Cape\"",
    "story-kokoro-stage3-3-1": "*From the Bottom of the Old, Dark Well*",
    "story-kokoro-stage3-3-2": "*From the Bottom of the Old, Dark Well*",
    "story-kokoro-stage3-3-3": "*From the Bottom of the Old, Dark Well*",
    "player-reimu(0)-1": "Spirit Sign \"Fantasy Seal\"",
    "player-marisa(1)-1": "Love Sign \"Master Spark\"",
    "player-kasen(10)-1": "Wrap Sign \"Prosthetic Arm Proteus\"",
    "player-ichirin(2)-1": "Storm Sign\n\"Autumn Storm Clouds of Buddhist Retribution\"",
    "player-hijiri(3)-1": "Heaven Sign\n\"Master of the Great Trichiliocosm\"",
    "player-futo(4)-1": "Wind Sign \"Miwa Plate Storm\"",
    "player-miko(5)-1": "Hermit Sign\n\"Taoist of the Land of the Rising Sun\"",
    "player-mamizou(8)-1": "Transformation\n\"Bunbuku Hot Soup Bathtub\"",
    "player-mokou(11)-1": "Blaze Sign\n\"Self-Destruction Giant Flame Whirlwind\"",
    "player-sinmyoumaru(12)-1": "Mallet \"Lavish Banquet of Legend\"",
    "player-nitori(6)-1": "Heavy Rain \"Great War Beneath the River\"",
    "player-koishi(7)-1": "Suppression \"Superego\"",
    "player-kokoro(9)-1": "Angry Mask \"Mask of an Angry Hated Wolf\"",
    "player-usami(13)-1": "Gun Sign \"3D Printer Gun\""
}