{
    "story-reimuB-stage1-2-1": "Unidentified \"Scrolls of Flying Objects\"",
    "story-reimuB-stage1-3-1": "*Crowded Alien Ball*",
    "story-reimuB-stage1-4-1": "*Let's Go Home Soon, Aliens!*",
    "story-reimuB-stage2-2-1": "Flame Sign \"Phoenix's Super-High-Temperature Feathers\"",
    "story-reimuB-stage2-3-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-reimuB-stage3-2-1": "Thunder Sign \"Slow-Speed Mukou\"",
    "story-reimuB-stage3-3-1": "*Hand that Grants Wishes Until Death*",
    "story-reimuB-stage3-4-1": "*The Monkey's Paw Dreams of the Occult*",
    "story-reimuB-stage4-2-1": "Psychokinesis \"Psychexplosion\"",
    "story-reimuB-stage4-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-reimuB-stage4-4-1": "*Occultician of the Present World*",
    "story-reimuB-stage4-5-1": "*Esoteric Seven of Profound Secrets*",
    "story-marisa-stage1-2-1": "Charm \"Shrine Prosperity Prayer Talismans\"",
    "story-marisa-stage2-2-1": "Water Sign \"Summer Plastic Bottle Rocket\"",
    "story-marisa-stage3-1-1": "*Cursed Dial-and-Drop Phone*",
    "story-marisa-stage4-2-1": "Virtue Sign \"Prestige of Shoutoku\"",
    "story-marisa-stage4-3-1": "*Hand that Grants Wishes Until Death*",
    "story-marisa-stage4-4-1": "Light Sign \"Lasers of Infinite Articles",
    "story-marisa-stage5-2-1": "\"Benten Lute Priest",
    "story-marisa-stage5-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-marisa-stage5-4-1": "*Occultician of the Present World*",
    "story-hijiri-stage1-2-1": "Throwing Dishes \"Kawarake Rotary Throw\"",
    "story-hijiri-stage2-2-1": "Star Sign \"Millisecond Pulsar\"",
    "story-hijiri-stage3-1-1": "*Perfect Nessie Cultivation Method*",
    "story-hijiri-stage4-2-1": "Virtue Sign \"Prestige of Shoutoku\"",
    "story-hijiri-stage4-3-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-hijiri-stage5-2-1": "\"Gautama Buddha At the Shinto Shrine\"",
    "story-hijiri-stage5-3-1": "*The Great Fiend's Arteries and Veins*",
    "story-hijiri-stage5-4-1": "*Fiend of the Century, 'Red Cape Blue Cape'*",
    "story-miko-stage1-2-1": "Charm \"Shrine Prosperity Prayer Talismans\"",
    "story-miko-stage2-2-1": "Star Sign \"Millisecond Pulsar\"",
    "story-miko-stage3-1-1": "*Perfect Nessie Cultivation Method*",
    "story-miko-stage4-2-1": "Pestle Sign \"Vajrapani's Incantation\"",
    "story-miko-stage4-3-1": "*Country of Illusion, Blefuscu*",
    "story-miko-stage5-2-1": "\"Playtime's Over!\"",
    "story-miko-stage5-3-1": "*Highway Turbo Air Turn*",
    "story-miko-stage5-4-1": "*Turbo Granny Rides for Her Life*",
    "story-ichirin-stage1-2-1": "Star Sign \"Millisecond Pulsar\"",
    "story-ichirin-stage2-2-1": "Charm \"Shrine Prosperity Prayer Talismans\"",
    "story-ichirin-stage3-2-1": "Water Sign \"Summer Plastic Bottle Rocket\"",
    "story-ichirin-stage3-3-1": "*Country of Illusion, Blefuscu*",
    "story-ichirin-stage4-2-1": "Instinct \"Freudian\"",
    "story-ichirin-stage4-3-1": "*The Great Fiend's Arteries and Veins*",
    "story-ichirin-stage4-4-1": "Thorn Sign \"Confined Innocent\"",
    "story-futo-stage1-2-1": "Star Sign \"Millisecond Pulsar\"",
    "story-futo-stage2-2-1": "Instinct \"Freudian\"",
    "story-futo-stage3-2-1": "Fist Sign \"Great Cumulus of Rage\"",
    "story-futo-stage3-3-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-futo-stage4-2-1": "Water Sign \"Summer Plastic Bottle Rocket\"",
    "story-futo-stage4-3-1": "*Highway Turbo Air Turn*",
    "story-futo-stage4-4-1": "Youkai Battleship \"Sanpei Fighter\"",
    "story-nitori-stage1-2-1": "Pestle Sign \"Vajrapani's Incantation\"",
    "story-nitori-stage2-2-1": "Fist Sign \"Great Cumulus of Rage\"",
    "story-nitori-stage3-2-1": "Star Sign \"Millisecond Pulsar\"",
    "story-nitori-stage3-3-1": "*'South Wind, Fine Weather, Clear Sky' Kick*",
    "story-nitori-stage4-2-1": "Charm \"Shrine Prosperity Prayer Talismans\"",
    "story-nitori-stage4-3-1": "*Crowded Alien Ball*",
    "story-nitori-stage4-4-1": "Charm \"Fantastic High-Speed Prayer Talismans\"",
    "story-koishi-stage1-2-1": "Virtue Sign \"Prestige of Shoutoku\"",
    "story-koishi-stage2-2-1": "Throwing Dishes \"Kawarake Rotary Throw\"",
    "story-koishi-stage3-2-1": "Star Sign \"Millisecond Pulsar\"",
    "story-koishi-stage3-3-1": "*Hand that Grants Wishes Until Death*",
    "story-koishi-stage3-4-1": "Magic Sign \"Blaze Away\"",
    "story-koishi-stage4-2-1": "Fist Sign \"Great Cumulus of Rage\"",
    "story-koishi-stage4-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-koishi-stage4-4-1": "Nyuudou \"Genso-Tarou Cloud in Summer\"",
    "story-mamizou-stage1-2-1": "Fist Sign \"Great Cumulus of Rage\"",
    "story-mamizou-stage2-2-1": "Throwing Dishes \"Kawarake Rotary Throw\"",
    "story-mamizou-stage3-1-1": "*Split-Mouthed Emotion*",
    "story-mamizou-stage4-2-1": "Virtue Sign \"Prestige of Shoutoku\"",
    "story-mamizou-stage4-3-1": "*Hand that Grants Wishes Until Death*",
    "story-mamizou-stage4-4-1": "Light Sign \"Lasers of Infinite Articles",
    "story-mamizou-stage5-2-1": "Charm \"Shrine Prosperity Prayer Talismans\"",
    "story-mamizou-stage5-3-1": "Psychokinesis \"Telekinesis: Illegal Dumping\"",
    "story-mamizou-stage5-4-1": "Charm \"Fantastic High-Speed Prayer Talismans\"",
    "story-kokoro-stage1-2-1": "Fist Sign \"Great Cumulus of Rage\"",
    "story-kokoro-stage2-1-1": "*Perfect Nessie Cultivation Method*",
    "story-kokoro-stage3-2-1": "Instinct \"Freudian\"",
    "story-kokoro-stage3-3-1": "*From the Bottom of the Old, Dark Well*",
    "story-kokoro-stage4-2-1": "Throwing Dishes \"Kawarake Rotary Throw\"",
    "story-kokoro-stage4-3-1": "*The Great Fiend's Arteries and Veins*",
    "story-kokoro-stage4-4-1": "Bow Sign \"Star Dragon Bow\"",
    "player-reimu(0)-1": "Youkai Buster",
    "player-reimu(0)-2": "Quick-Witted Consecration Talismans",
    "player-reimu(0)-3": "Mid-Air Ascension Kick",
    "player-marisa(1)-1": "Witch Leyline",
    "player-marisa(1)-2": "Rising Sweep",
    "player-marisa(1)-3": "Witching Blast",
    "player-kasen(10)-1": "Wrap Sign \"Prosthetic Arm Proteus\"",
    "player-kasen(10)-2": "Dragon Sign \"Dragon's Growl\"",
    "player-kasen(10)-3": "Hawk Sign \"Hawk Beacon\"",
    "player-ichirin(2)-1": "Hanging Cloud's Iron Hammer",
    "player-ichirin(2)-2": "Handful of Floating Cloud",
    "player-ichirin(2)-3": "Small Thunder Cloud",
    "player-hijiri(3)-1": "Hanuman's Dance",
    "player-hijiri(3)-2": "Virupaksa's Eyes",
    "player-hijiri(3)-3": "Indra's Thunder",
    "player-futo(4)-1": "Wind's Ominous Hole",
    "player-futo(4)-2": "Royal Dragon's Arrow",
    "player-futo(4)-3": "Water-Embracing Plates",
    "player-miko(5)-1": "Shukuchi Cape",
    "player-miko(5)-2": "Lasers of Seventeen Articles",
    "player-miko(5)-3": "Wishful Soul of Desire",
    "player-mamizou(8)-1": "Utsusemi Jizo Transformation",
    "player-mamizou(8)-2": "Bizarre Okuri-Chouchin",
    "player-mamizou(8)-3": "Animal Lute Priest",
    "player-mokou(11)-1": "Blaze Sign\n\"Self-Destruction Giant Flame Whirlwind\"",
    "player-mokou(11)-2": "Undying\n\"'South Wind, Clear Sky' Soaring Kick\"",
    "player-mokou(11)-3": "Cursed Talisman\n\"Indiscriminate Ignition Cards\"",
    "player-sinmyoumaru(12)-1": "Mallet \"Lavish Banquet of Legend\"",
    "player-sinmyoumaru(12)-2": "Inchling\n\"One-Inch Samurai with a Half-Inch Soul\"",
    "player-sinmyoumaru(12)-3": "Fishing Sign\n\"Adorable Tai Gong Wang\"",
    "player-nitori(6)-1": "Aerial Blaster",
    "player-nitori(6)-2": "Photon Torpedo",
    "player-nitori(6)-3": "Farewell Rubber Ring",
    "player-koishi(7)-1": "Conditioned Teleport",
    "player-koishi(7)-2": "Fidgety Snatcher",
    "player-koishi(7)-3": "Growing Pain",
    "player-kokoro(9)-1": "Roaring Youkai Fox Mask",
    "player-kokoro(9)-2": "Shouting Giant Spider Mask",
    "player-kokoro(9)-3": "Sighing Osakabe Mask",
    "player-usami(13)-1": "Gun Sign \"3D Printer Gun\"",
    "player-usami(13)-2": "Psychokinesis \"Psychokinesis App\"",
    "player-usami(13)-3": "Psychokinesis \"Telekinesis: Radio Tower\"",
    "story-reimu-stage1-2-1": "Star Sign \"Millisecond Pulsar\"",
    "story-reimu-stage2-2-1": "Fist Sign \"Great Cumulus of Rage\"",
    "story-reimu-stage2-4-1": "Nyuudou \"Genso-Tarou Cloud in Summer\"",
    "story-reimu-stage3-2-1": "Throwing Dishes \"Kawarake Rotary Throw\"",
    "story-reimu-stage3-4-1": "Bow Sign \"Star Dragon Bow\"",
    "story-reimu-stage4-2-1": "Pestle Sign \"Vajrapani's Incantation\"",
    "story-reimu-stage4-4-1": "Superhuman \"Garuda's Wings\"",
    "story-reimu-stage5-2-1": "\"Playtime's Over!\"",
    "story-reimu-stage6-2-1": "Transformation \"Garden of Flowers and Birds on a Full Moon\"",
    "story-reimu-stage6-4-1": "Transformation \"Scrolls of Frolicking Animals\"",
    "story-reimu-stage6-6-1": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "story-reimu-stage7-2-1": "Melancholy Sign \"The Melancholic World is a Melancholic Cart\"",
    "story-reimu-stage7-4-1": "Joy Sign \"Invigorated Kagura Lion\"",
    "story-reimu-stage7-6-1": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "story-reimu-stage7-8-1": "\"Monkey Possession\"",
    "story-marisa-stage2-4-1": "Youkai Battleship \"Sanpei Fighter\"",
    "story-marisa-stage3-2-1": "Instinct \"Freudian\"",
    "story-marisa-stage3-4-1": "Thorn Sign \"Confined Innocent\"",
    "story-marisa-stage6-2-1": "Transformation \"Garden of Flowers and Birds on a Full Moon\"",
    "story-marisa-stage6-4-1": "Transformation \"Scrolls of Frolicking Animals\"",
    "story-marisa-stage6-6-1": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "story-marisa-stage7-2-1": "Melancholy Sign \"The Melancholic World is a Melancholic Cart\"",
    "story-marisa-stage7-4-1": "Joy Sign \"Invigorated Kagura Lion\"",
    "story-marisa-stage7-6-1": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "story-marisa-stage7-8-1": "\"Monkey Possession\"",
    "story-hijiri-stage2-4-1": "Magic Sign \"Blaze Away\"",
    "story-hijiri-stage3-2-1": "Charm \"Shrine Prosperity Prayer Talismans\"",
    "story-hijiri-stage3-4-1": "Charm \"Fantastic High-Speed Prayer Talismans\"",
    "story-hijiri-stage4-4-1": "Light Sign \"Lasers of Infinite Articles",
    "story-hijiri-stage6-2-1": "Transformation \"Garden of Flowers and Birds on a Full Moon\"",
    "story-hijiri-stage6-4-1": "Transformation \"Scrolls of Frolicking Animals\"",
    "story-hijiri-stage6-6-1": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "story-hijiri-stage7-2-1": "Melancholy Sign \"The Melancholic World is a Melancholic Cart\"",
    "story-hijiri-stage7-4-1": "Joy Sign \"Invigorated Kagura Lion\"",
    "story-hijiri-stage7-6-1": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "story-hijiri-stage7-8-1": "\"Monkey Possession\"",
    "story-miko-stage2-4-1": "Magic Sign \"Blaze Away\"",
    "story-miko-stage3-2-1": "Fist Sign \"Great Cumulus of Rage\"",
    "story-miko-stage3-4-1": "Nyuudou \"Genso-Tarou Cloud in Summer\"",
    "story-miko-stage4-4-1": "Superhuman \"Garuda's Wings\"",
    "story-miko-stage6-2-1": "Transformation \"Garden of Flowers and Birds on a Full Moon\"",
    "story-miko-stage6-4-1": "Transformation \"Scrolls of Frolicking Animals\"",
    "story-miko-stage6-6-1": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "story-miko-stage7-2-1": "Melancholy Sign \"The Melancholic World is a Melancholic Cart\"",
    "story-miko-stage7-4-1": "Joy Sign \"Invigorated Kagura Lion\"",
    "story-miko-stage7-6-1": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "story-miko-stage7-8-1": "\"Monkey Possession\"",
    "story-ichirin-stage2-4-1": "Charm \"Fantastic High-Speed Prayer Talismans\"",
    "story-ichirin-stage3-4-1": "Youkai Battleship \"Sanpei Fighter\"",
    "story-ichirin-stage5-2-1": "\"Benten Lute Priest",
    "story-ichirin-stage6-2-1": "Transformation \"Garden of Flowers and Birds on a Full Moon\"",
    "story-ichirin-stage6-4-1": "Transformation \"Scrolls of Frolicking Animals\"",
    "story-ichirin-stage6-6-1": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "story-ichirin-stage7-2-1": "Melancholy Sign \"The Melancholic World is a Melancholic Cart\"",
    "story-ichirin-stage7-4-1": "Joy Sign \"Invigorated Kagura Lion\"",
    "story-ichirin-stage7-6-1": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "story-ichirin-stage7-8-1": "\"Monkey Possession\"",
    "story-futo-stage2-4-1": "Thorn Sign \"Confined Innocent\"",
    "story-futo-stage3-4-1": "Nyuudou \"Genso-Tarou Cloud in Summer\"",
    "story-futo-stage5-2-1": "\"Playtime's Over!\"",
    "story-futo-stage6-2-1": "Transformation \"Garden of Flowers and Birds on a Full Moon\"",
    "story-futo-stage6-4-1": "Transformation \"Scrolls of Frolicking Animals\"",
    "story-futo-stage6-6-1": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "story-futo-stage7-2-1": "Melancholy Sign \"The Melancholic World is a Melancholic Cart\"",
    "story-futo-stage7-4-1": "Joy Sign \"Invigorated Kagura Lion\"",
    "story-futo-stage7-6-1": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "story-futo-stage7-8-1": "\"Monkey Possession\"",
    "story-nitori-stage2-4-1": "Nyuudou \"Genso-Tarou Cloud in Summer\"",
    "story-nitori-stage3-4-1": "Magic Sign \"Blaze Away\"",
    "story-nitori-stage5-2-1": "\"Playtime's Over!\"",
    "story-nitori-stage6-2-1": "Transformation \"Garden of Flowers and Birds on a Full Moon\"",
    "story-nitori-stage6-4-1": "Transformation \"Scrolls of Frolicking Animals\"",
    "story-nitori-stage6-6-1": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "story-nitori-stage7-2-1": "Melancholy Sign \"The Melancholic World is a Melancholic Cart\"",
    "story-nitori-stage7-4-1": "Joy Sign \"Invigorated Kagura Lion\"",
    "story-nitori-stage7-6-1": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "story-nitori-stage7-8-1": "\"Monkey Possession\"",
    "story-koishi-stage2-4-1": "Bow Sign \"Star Dragon Bow\"",
    "story-koishi-stage5-2-1": "\"Gautama Buddha At the Shinto Shrine\"",
    "story-koishi-stage6-2-1": "Transformation \"Garden of Flowers and Birds on a Full Moon\"",
    "story-koishi-stage6-4-1": "Transformation \"Scrolls of Frolicking Animals\"",
    "story-koishi-stage6-6-1": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "story-koishi-stage7-2-1": "Melancholy Sign \"The Melancholic World is a Melancholic Cart\"",
    "story-koishi-stage7-4-1": "Joy Sign \"Invigorated Kagura Lion\"",
    "story-koishi-stage7-6-1": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "story-koishi-stage7-8-1": "\"Monkey Possession\"",
    "story-mamizou-stage2-4-1": "Bow Sign \"Star Dragon Bow\"",
    "story-mamizou-stage3-2-1": "Water Sign \"Summer Plastic Bottle Rocket\"",
    "story-mamizou-stage3-4-1": "Superhuman \"Garuda's Wings\"",
    "story-mamizou-stage5-6-1": "Charm \"Anti-Youkai Houi-Yoke Prayer\"",
    "story-mamizou-stage6-2-1": "Melancholy Sign \"The Melancholic World is a Melancholic Cart\"",
    "story-mamizou-stage6-4-1": "Joy Sign \"Invigorated Kagura Lion\"",
    "story-mamizou-stage6-6-1": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "story-mamizou-stage6-8-1": "\"Monkey Possession\"",
    "story-kokoro-stage2-2-1": "Water Sign \"Summer Plastic Bottle Rocket\"",
    "story-kokoro-stage2-4-1": "Youkai Battleship \"Sanpei Fighter\"",
    "story-kokoro-stage3-4-1": "Thorn Sign \"Confined Innocent\"",
    "story-kokoro-stage5-2-1": "Star Sign \"Millisecond Pulsar\"",
    "story-kokoro-stage5-4-1": "Magic Sign \"Blaze Away\"",
    "story-kokoro-stage6-2-1": "Transformation \"Garden of Flowers and Birds on a Full Moon\"",
    "story-kokoro-stage6-4-1": "Transformation \"Scrolls of Frolicking Animals\"",
    "story-kokoro-stage6-6-1": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "story-kokoro-stage7-2-1": "\"Faith-Augmentation Prayer Ceremony\"",
    "story-kokoro-stage7-4-1": "\"Main Two Religions' Nine-Syllable Self-Defense\"",
    "story-kokoro-stage7-6-1": "\"Great Menreiki Expulsion\"",
    "story-kokoro-stage7-8-1": "\"Trinity Religion Finale\"",
    "player-reimu(0)-4": "Dimensional Point Rift",
    "player-reimu(0)-5": "Yin-Yang Shot",
    "player-reimu(0)-6": "Frontal Defense Talisman",
    "player-reimu(0)-7": "Floating Wall Jump",
    "player-reimu(0)-8": "Spirit Sign \"Fantasy Seal\"",
    "player-reimu(0)-9": "Treasure \"Ying-Yang Asuka'i\"",
    "player-reimu(0)-10": "Divine Arts \"Omnidirectional Dragon-Slaying Circle\"",
    "player-marisa(1)-4": "Strato Fraction",
    "player-marisa(1)-5": "Sweep Aside",
    "player-marisa(1)-6": "Powerful Drug",
    "player-marisa(1)-7": "Luminary Shot",
    "player-marisa(1)-8": "Love Sign \"Master Spark\"",
    "player-marisa(1)-9": "Comet \"Blazing Star\"",
    "player-marisa(1)-10": "Star Sign \"Satellite Illusion\"",
    "player-ichirin(2)-4": "Raging Running Cloud",
    "player-ichirin(2)-5": "Sunrise of Mountain Clouds",
    "player-ichirin(2)-6": "Drifting Cloud of Bludgeoning",
    "player-ichirin(2)-7": "North Mountain Wind of Mercy",
    "player-ichirin(2)-8": "Storm Sign \"Autumn Storm Clouds of Buddhist Retribution\"",
    "player-ichirin(2)-9": "Cumulonimbus \"Foreseeing Nyuudou Cloud\"",
    "player-ichirin(2)-10": "Clenched Fist \"Deadly Wind of Penitence\"",
    "player-hijiri(3)-4": "Skanda's Legs",
    "player-hijiri(3)-5": "Virudhaka's Sword",
    "player-hijiri(3)-6": "Garuda's Talons",
    "player-hijiri(3)-7": "Durga's Soul",
    "player-hijiri(3)-8": "Heaven Sign \"Master of the Great Trichiliocosm\"",
    "player-hijiri(3)-9": "Heaven Sign \"Brilliance of Mahavairocana\"",
    "player-hijiri(3)-10": "Heaven Sign \"Five-Element Mountain of Shakyamuni\"",
    "player-futo(4)-4": "Ame-no-Iwafune",
    "player-futo(4)-5": "Liuren Holy Fire",
    "player-futo(4)-6": "Standing Mountain",
    "player-futo(4)-7": "Combination Wind",
    "player-futo(4)-8": "Wind Sign \"Miwa Plate Storm\"",
    "player-futo(4)-9": "Blaze Sign \"Taiyi True Fire\"",
    "player-futo(4)-10": "Fate \"Gate Opening for Catastrophe\"",
    "player-miko(5)-4": "Cipangu the Golden Sword",
    "player-miko(5)-5": "Influence of the East",
    "player-miko(5)-6": "Tenfold Listening",
    "player-miko(5)-7": "Benign Rain from the Shining One",
    "player-miko(5)-8": "Hermit Sign \"Taoist of the Land of the Rising Sun\"",
    "player-miko(5)-9": "Tao Sign \"Heavenly Way Atop One's Palm\"",
    "player-miko(5)-10": "Human Sign \"Tradition of Just Rewards\"",
    "player-nitori(6)-4": "Criminal Gear",
    "player-nitori(6)-5": "Water Bomb Giant Swing",
    "player-nitori(6)-6": "Kiku-ichimonji Compressor",
    "player-nitori(6)-7": "Q-Cumber Sound System",
    "player-nitori(6)-8": "Heavy Rain \"Great War Beneath the River\"",
    "player-nitori(6)-9": "Bubble Sign \"Fire! Bubble Dragon\"",
    "player-nitori(6)-10": "Battle Machine \"Fly! Sanpei Fight\"",
    "player-koishi(7)-4": "Catch and Rose",
    "player-koishi(7)-5": "Reflex Radar",
    "player-koishi(7)-6": "Stinging Mind",
    "player-koishi(7)-7": "Unanswered Love",
    "player-koishi(7)-8": "Suppression \"Superego\"",
    "player-koishi(7)-9": "Instinct \"Release of the Id\"",
    "player-koishi(7)-10": "Dream Sign \"Ancestors are Watching You\"",
    "player-mamizou(8)-4": "Youkai Amikiri Transformation",
    "player-mamizou(8)-5": "Youkai Karakasa Transformation",
    "player-mamizou(8)-6": "Youkai Tsurube Transformation",
    "player-mamizou(8)-7": "Youkai Omokage Transformation",
    "player-mamizou(8)-8": "Transformation \"Bunbuku Hot Soup Bathtub\"",
    "player-mamizou(8)-9": "Transformation \"Youkai World Gate of One Hundred Demons\"",
    "player-mamizou(8)-10": "Transformation \"Futatsuiwa Clan's Curse\"",
    "player-kokoro(9)-4": "Melancholic Ogress Mask",
    "player-kokoro(9)-5": "Delighted Lion Mask",
    "player-kokoro(9)-6": "Enraptured Hyottoko Mask",
    "player-kokoro(9)-7": "Kokoro Roulette",
    "player-kokoro(9)-8": "Anger Sign \"Mask of an Angry Hated Wolf\"",
    "player-kokoro(9)-9": "Possession \"Four Humors Possession\"",
    "player-kokoro(9)-10": "Melancholy Mask \"The Man of Qi Worries about the Earth\"",
    "player-common(10)-1": "Spiritual Strike Talisman",
    "player-common(10)-2": "Magic Mushroom",
    "player-common(10)-3": "Virtueless Dharmacakra",
    "player-common(10)-4": "Witch's Broom",
    "player-common(10)-5": "Pagoda of Bishamonten",
    "player-common(10)-6": "Hermit Wind Plate",
    "player-common(10)-7": "Stern Shaku",
    "player-common(10)-8": "Force Shield",
    "player-common(10)-10": "Common Talisman",
    "player-common(10)-11": "Hermit's Decorative Sword",
    "player-common(10)-12": "Prayer Beads to Hide in the Bosom",
    "player-common(10)-13": "Innocent Hat"
}